Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2020-12, with the labels that each got.

#17 Adding changes from #11
  doc/jp/components/category-chart.md
  doc/jp/components/data-chart-axis-annotations.md
  doc/jp/components/data-chart-axis-locations.md
  doc/jp/components/data-chart-axis-types.md
  doc/jp/components/data-chart-synchronization.md
  doc/jp/components/data-chart-type-category-series.md
  doc/jp/components/data-chart-type-category-step-area-series.md
  doc/jp/components/data-chart-type-category-step-line-series.md
  doc/jp/components/data-chart-type-financial-area-indicators.md
  doc/jp/components/data-chart-type-financial-candlestick-series.md
  doc/jp/components/data-chart-type-financial-column-indicators.md
  doc/jp/components/data-chart-type-financial-line-indicators.md
  doc/jp/components/data-chart-type-financial-ohlc-series.md
  doc/jp/components/data-chart-type-financial-overlays.md
  doc/jp/components/data-chart-type-polar-series.md
  doc/jp/components/data-chart-type-radial-line-series.md
  doc/jp/components/data-chart-type-radial-pie-series.md
  doc/jp/components/data-chart-type-radial-series.md
  doc/jp/components/data-chart-type-range-series.md
  doc/jp/components/data-chart-type-scatter-area-series.md
  doc/jp/components/data-chart-type-scatter-bubble-series.md
  doc/jp/components/data-chart-type-scatter-contour-series.md
  doc/jp/components/data-chart-type-scatter-point-series.md
  doc/jp/components/data-chart-type-shape-series.md
  doc/jp/components/data-chart-type-stacked-series.md
  doc/jp/components/data-chart-value-overlay.md
  doc/jp/components/data-chart.md
  doc/jp/components/data-grid-accessibility.md
  doc/jp/components/data-grid-row-highlighting.md
  doc/jp/components/data-grid.md
  doc/jp/components/financial-chart-multiple-data.md
  doc/jp/components/general-breaking-changes-dv.md
  doc/jp/components/general-getting-started.md
  docfx/jp/components/toc.json
Labels: area: localization, status: verified

#18 Add dock manager active pane and localization docs
  doc/en/components/dock-manager.md
Labels: status: verified

#21 Updating JP - vnext
  doc/jp/components/data-grid-cell-editing.md
  doc/jp/components/data-grid.md
  doc/jp/components/grids.md
  doc/jp/components/multi-column-combobox.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#36 Localization 1012 vnext
  doc/jp/components/data-chart-axis-types.md
  doc/jp/components/data-chart-navigation.md
  doc/jp/components/data-chart-series-markers.md
  doc/jp/components/data-chart-type-financial-area-indicators.md
  doc/jp/components/data-chart-type-financial-candlestick-series.md
  doc/jp/components/data-chart-type-financial-column-indicators.md
  doc/jp/components/data-chart-type-financial-line-indicators.md
  doc/jp/components/data-chart-type-financial-series.md
  doc/jp/components/data-chart-type-scatter-bubble-series.md
  doc/jp/components/data-chart-type-scatter-contour-series.md
  doc/jp/components/data-chart.md
  doc/jp/components/data-grid-accessibility.md
  doc/jp/components/data-grid-cell-editing.md
  doc/jp/components/data-grid-column-types.md
  doc/jp/components/data-grid.md
  doc/jp/components/date-picker.md
  doc/jp/components/doughnut-chart.md
  doc/jp/components/excel-library-using-cells.md
  doc/jp/components/excel-library-using-tables.md
  doc/jp/components/excel-library-using-workbooks.md
  doc/jp/components/excel-library-using-worksheets.md
  doc/jp/components/excel-library-working-with-charts.md
  doc/jp/components/excel-library-working-with-sparklines.md
  doc/jp/components/excel-library.md
  doc/jp/components/excel-utility.md
  doc/jp/components/financial-chart-high-frequency.md
  doc/jp/components/general-breaking-changes-dv.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/general-licensing.md
  doc/jp/components/geo-map-binding-multiple-shapes.md
  doc/jp/components/geo-map-display-heat-imagery.md
  doc/jp/components/geo-map-resources-world-connections.md
  doc/jp/components/geo-map-shape-styling.md
  doc/jp/components/multi-column-combobox.md
  doc/jp/components/nuget-feed.md
  doc/jp/components/sparkline.md
  doc/jp/components/spreadsheet-configuring.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified
