Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-03, with the labels that each got.

#68 Mdd seo descriptions
  doc/en/components/charts/chart-types-area.md
  doc/en/components/charts/chart-types-bar.md
  doc/en/components/charts/chart-types-bubble.md
  doc/en/components/charts/chart-types-column.md
  doc/en/components/charts/chart-types-doughnut.md
  doc/en/components/charts/chart-types-financial.md
  doc/en/components/charts/chart-types-line.md
  doc/en/components/charts/chart-types-pie.md
  doc/en/components/charts/chart-types-polar.md
  doc/en/components/charts/chart-types-radial.md
  doc/en/components/charts/chart-types-scatter.md
  doc/en/components/charts/chart-types-shape.md
  doc/en/components/charts/chart-types-spline.md
  doc/en/components/charts/chart-types-step.md
  docfx/en/components/toc.json
Labels: status: in-review

#64 Updating JP - vnext
  doc/jp/components/charts/chart-type-overview.md
  doc/jp/components/charts/chart-types-area.md
  doc/jp/components/charts/chart-types-bar.md
  doc/jp/components/charts/chart-types-bubble.md
  doc/jp/components/charts/chart-types-column.md
  doc/jp/components/charts/chart-types-doughnut.md
  doc/jp/components/charts/chart-types-financial.md
  doc/jp/components/charts/chart-types-line.md
  doc/jp/components/charts/chart-types-pie.md
  doc/jp/components/charts/chart-types-polar.md
  doc/jp/components/charts/chart-types-radial.md
  doc/jp/components/charts/chart-types-scatter.md
  doc/jp/components/charts/chart-types-shape.md
  doc/jp/components/charts/chart-types-spline.md
  doc/jp/components/charts/chart-types-step.md
  doc/jp/components/data-grid-cell-editing.md
  doc/jp/components/doughnut-chart.md
  doc/jp/components/pie-chart.md
  doc/jp/images/charts/ignite-ui-angular-category-chart-high-volume-data-1100.gif
  doc/jp/images/charts/ignite-ui-angular-financial-chart-custom-tooltips-1100.jpg
  doc/jp/images/charts/ignite-ui-angular-financial-chart-modular-design-1100.jpg
  doc/jp/images/charts/ignite-ui-angular-financial-chart-smart-data-binding-1100.jpg
  doc/jp/images/charts/ignite-ui-angular-financial-chart-trendlines-1100.jpg
  doc/jp/images/charts/ignite-ui-angular-financial-chart-zooming-1100.gif
  docfx/jp/components/toc.json
Labels: area: localization, status: localized

#72 Update chart-types-bubble.md
  doc/en/components/charts/chart-types-bubble.md
Labels: status: in-review

#79 mdd-seo-update
  doc/en/components/charts/chart-types-line.md
  doc/en/components/charts/chart-types-polar.md
  doc/en/components/charts/chart-types-radial.md
Labels: status: in-review

#81 "mdd-bug-fixing""
  doc/en/components/charts/chart-types-area.md
  doc/en/components/charts/chart-types-bar.md
  doc/en/components/charts/chart-types-bubble.md
  doc/en/components/charts/chart-types-column.md
  doc/en/components/charts/chart-types-doughnut.md
  doc/en/components/charts/chart-types-financial.md
  doc/en/components/charts/chart-types-line.md
  doc/en/components/charts/chart-types-pie.md
  doc/en/components/charts/chart-types-polar.md
  doc/en/components/charts/chart-types-radial.md
  doc/en/components/charts/chart-types-scatter.md
  doc/en/components/charts/chart-types-shape.md
  doc/en/components/charts/chart-types-spline.md
  doc/en/components/charts/chart-types-step.md
  docfx/en/components/toc.json
Labels: status: in-review

#80 Updating JP - vNext
  doc/jp/components/charts/chart-types-area.md
  doc/jp/components/charts/chart-types-bar.md
  doc/jp/components/charts/chart-types-bubble.md
  doc/jp/components/charts/chart-types-column.md
  doc/jp/components/charts/chart-types-doughnut.md
  doc/jp/components/charts/chart-types-financial.md
  doc/jp/components/charts/chart-types-line.md
  doc/jp/components/charts/chart-types-pie.md
  doc/jp/components/charts/chart-types-polar.md
  doc/jp/components/charts/chart-types-radial.md
  doc/jp/components/charts/chart-types-scatter.md
  doc/jp/components/charts/chart-types-shape.md
  doc/jp/components/charts/chart-types-spline.md
  doc/jp/components/charts/chart-types-step.md
  doc/jp/components/data-chart-series-highlighting.md
  doc/jp/components/data-chart-type-range-area-series.md
  doc/jp/components/data-chart-type-range-column-series.md
  doc/jp/components/geo-map-type-scatter-area-series.md
  doc/jp/components/geo-map-type-scatter-contour-series.md
  doc/jp/components/geo-map.md
  doc/jp/components/grids.md
Labels: status: awaiting-test, status: localized

#83 Update chart-features-annotations.md
  doc/en/components/charts/chart-features-annotations.md
Labels: status: in-review

#92 mdd-seo-value-overlays
  doc/en/components/charts/data-chart-value-overlays.md
  docfx/en/components/toc.json
Labels: status: in-review

#91 Mdd seo chart navigation&synchronization(missing samples at the moment)
  doc/en/components/charts/chart-features-navigation.md
  doc/en/components/charts/chart-features-synchronization.md
  docfx/en/components/toc.json
Labels: status: in-review

#86 Add cta banners
  doc/en/images/marketing/ignite-ui-blazor-cta-banner-2.png
  doc/en/images/marketing/ignite-ui-react-cta-banner-2.png
  doc/en/images/marketing/ignite-ui-web-components-cta-banner-2.png
  doc/jp/images/marketing/ignite-ui-blazor-cta-banner-2.png
  doc/jp/images/marketing/ignite-ui-react-cta-banner-2.png
  doc/jp/images/marketing/ignite-ui-web-components-cta-banner-2.png
  package.json
  yarn.lock
Labels: status: verified

#85 Update chart-features-animations.md
  doc/en/components/charts/chart-features-animations.md
Labels: status: in-review, status: resolved

#87 Update chart-features-markers.md
  doc/en/components/charts/chart-features-markers.md
Labels: status: in-review, status: resolved

#88 Update chart-features-tooltips.md
  doc/en/components/charts/chart-features-tooltips.md
Labels: area: bug

#90 "Update chart-features-trendlines.md""
  doc/en/components/charts/chart-features-trendlines.md
Labels: status: in-review, status: resolved

#84 Update chart-features-highlighting.md
  doc/en/components/charts/chart-features-highlighting.md
Labels: status: in-review, status: resolved

#93 mdd-seo-bug-fixing
  doc/en/components/charts/types/area-chart.md
  doc/en/components/charts/types/column-chart.md
  docfx/en/components/toc.json
Labels: status: in-review

#94 mdd-seo-treemap-without-styling
  doc/en/components/charts/types/treemap-chart.md
  docfx/en/components/toc.json
Labels: status: in-review

#96 Update treemap-chart.md
  doc/en/components/charts/types/treemap-chart.md
Labels: status: in-review
