Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-05, with the labels that each got.

#126 mdd-sample-fix
  doc/en/components/charts/types/composite-chart.md
  doc/jp/components/charts/types/composite-chart.md
Labels: status: in-review

#128 mdd-added-what's-new
  doc/en/components/general-breaking-changes-dv.md
  doc/en/components/general-whats-new-dv.md
  doc/en/images/chartDefaults1.png
  doc/en/images/chartDefaults2.png
  doc/en/images/chartDefaults3.png
  doc/en/images/chartDefaults4.png
  docConfig.json
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
  gulpfile.js
Labels: status: in-review

#125 Localization fixes
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/features/chart-annotations.md
  doc/jp/components/charts/features/chart-axis-gridlines.md
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/charts/types/treemap-chart.md
  doc/jp/components/excel-library-using-cells.md
  doc/jp/components/financial-chart-axis-types.md
  doc/jp/components/financial-chart-custom-indicators.md
  doc/jp/components/financial-chart-high-frequency.md
  doc/jp/components/financial-chart-trendlines.md
  doc/jp/components/financial-chart.md
  doc/jp/components/general-licensing.md
  doc/jp/components/geo-map-binding-multiple-shapes.md
  doc/jp/components/geo-map-display-bing-imagery.md
  doc/jp/components/geo-map-display-imagery-types.md
  doc/jp/components/geo-map-navigation.md
  doc/jp/components/pie-chart.md
  doc/jp/components/radial-gauge.md
  doc/jp/components/spreadsheet-activation.md
  doc/jp/components/spreadsheet-commands.md
  doc/jp/components/spreadsheet-configuring.md
  doc/jp/components/spreadsheet-hyperlinks.md
  docfx/jp/components/toc.json
Labels: area: localization, status: verified

#124 Add sample for pane hiding
  doc/en/components/dock-manager.md
Labels: status: publish-pending

#115 Mdd 21.1 date picker
  doc/en/components/charts/features/chart-tooltips.md
  doc/en/components/editors/date-picker.md
Labels: status: in-review

#123 Update chart-highlighting.md
  doc/en/components/charts/features/chart-highlighting.md
Labels: status: do not merge, status: in-review

#129 mdd-added-changelog
  doc/en/components/general-changelog-dv.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: in-review

#116 Mdd 21.1 data grid
  doc/en/components/data-grid-cell-activation.md
  doc/en/components/data-grid-cell-editing.md
  doc/en/components/data-grid-cell-selection.md
Labels: status: in-review

#133 Update excel-library-using-cells.md
  doc/en/components/excel-library-using-cells.md
Labels: status: in-review

#132 Mdd build flag angular title
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#135 Update toc.json
  docfx/en/components/toc.json
Labels: status: in-review

#136 Update general-changelog-dv.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review
