Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-11, with the labels that each got.

#199 [JA] Updating changelog
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/data-grid-cell-merging.md
  doc/jp/components/general-changelog-dv.md
Labels: area: localization, status: localized, status: verified

#193 mdd-update
  doc/en/components/data-grid-load-save-layout.md
  doc/jp/components/data-grid-load-save-layout.md
Labels: status: in-development

#203 docs(Calendar) topic
  doc/en/components/calendar.md
  docConfig.json
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#204 chore(*): Adding API Docs env variable.
  docfx/en/environment.json
Labels: area: api

#201 docs(link-button): add link button topic #194
  doc/en/components/link-button.md
  docfx/en/components/toc.json
Labels: area: docs

#187 docs(form): add topic - vNext
  doc/en/components/inputs/form.md
  doc/en/components/menus/navbar.md
  docConfig.json
  docfx/en/components/toc.json
Labels: area: docs

#205 docs(calendar): add API links
  doc/en/components/calendar.md
Labels: area: docs, status: verified

#196 docs(nav-drawer): Add nav-drawer topic
  doc/en/components/menus/navigation-drawer.md
  docfx/en/components/toc.json
Labels: area: docs

#206 fix(SEO): replace class name in 1st paragraph
  doc/en/components/inputs/form.md
Labels: area: docs

#200 docs(card) topic
  doc/en/components/layouts/card.md
  doc/en/components/layouts/dock-manager-electron.md
  doc/en/components/layouts/dock-manager-embedding-frames.md
  doc/en/components/layouts/dock-manager-updating-panes.md
  doc/en/components/layouts/dock-manager.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#191 docs(button): add button topic #174
  doc/en/components/inputs/button.md
  doc/en/components/inputs/link-button.md
  docfx/en/components/toc.json
Labels: area: docs

#176 docs(list): add topic for list web component
  doc/en/components/grids/data-grid-accessibility.md
  doc/en/components/grids/data-grid-cell-activation.md
  doc/en/components/grids/data-grid-cell-editing.md
  doc/en/components/grids/data-grid-cell-merging.md
  doc/en/components/grids/data-grid-cell-selection.md
  doc/en/components/grids/data-grid-column-animation.md
  doc/en/components/grids/data-grid-column-chooser.md
  doc/en/components/grids/data-grid-column-filtering.md
  doc/en/components/grids/data-grid-column-moving.md
  doc/en/components/grids/data-grid-column-options.md
  doc/en/components/grids/data-grid-column-pinning.md
  doc/en/components/grids/data-grid-column-resizing.md
  doc/en/components/grids/data-grid-column-sorting.md
  doc/en/components/grids/data-grid-column-summaries.md
  doc/en/components/grids/data-grid-column-types.md
  doc/en/components/grids/data-grid-horizontal-scrolling.md
  doc/en/components/grids/data-grid-live-data.md
  doc/en/components/grids/data-grid-load-save-layout.md
  doc/en/components/grids/data-grid-local-data.md
  doc/en/components/grids/data-grid-performance.md
  doc/en/components/grids/data-grid-remote-data.md
  doc/en/components/grids/data-grid-row-grouping.md
  doc/en/components/grids/data-grid-row-highlighting.md
  doc/en/components/grids/data-grid-row-paging.md
  doc/en/components/grids/data-grid-row-pinning.md
  doc/en/components/grids/data-grid-type-comparison-table.md
  doc/en/components/grids/data-grid-type-heatmap-table.md
  doc/en/components/grids/data-grid-type-matrix-table.md
  doc/en/components/grids/data-grid-type-periodic-table.md
  doc/en/components/grids/data-grid-type-sparkline-table.md
  doc/en/components/grids/data-grid.md
  doc/en/components/grids/grids.md
  doc/en/components/grids/list.md
  docfx/en/components/toc.json
Labels: area: docs, status: translating, status: verified

#209 fix(*): Merged linkbutton into button.
  doc/en/components/inputs/button.md
  doc/en/components/inputs/link-button.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#207 [JA] Latest localization changes
  doc/jp/components/calendar.md
  doc/jp/components/dock-manager-electron.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/inputs/form.md
  doc/jp/components/link-button.md
  doc/jp/components/menus/navbar.md
  docfx/jp/components/toc.json
  docfx/jp/environment.json
Labels: area: localization, status: localized, status: verified

#211 fix(*): Updated import info.
  doc/en/components/calendar.md
  doc/en/components/grids/list.md
  doc/en/components/inputs/form.md
  doc/en/components/layouts/card.md
  doc/en/components/menus/navbar.md
  doc/en/components/menus/navigation-drawer.md
  docfx/en/components/toc.json
Labels: status: in-test

#190 docs(radio): add topic
  doc/en/components/radio.md
  docfx/en/components/toc.json
Labels: area: docs

#189 docs(checkbox): add topic
  doc/en/components/checkbox.md
  docfx/en/components/toc.json
Labels: area: docs

#198 docs(ripple): add topic
  doc/en/components/ripple.md
  docfx/en/components/toc.json
Labels: area: docs

#188 docs(switch): add topic
  doc/en/components/switch.md
  docfx/en/components/toc.json
Labels: area: docs

#179 docs(avatar): add basic documentation
  doc/en/components/avatar.md
  docfx/en/components/toc.json
Labels: area: docs

#180 docs(badge): add topic
  doc/en/components/badge.md
  docfx/en/components/toc.json
Labels: area: docs

#216 docs(radio, checkbox): fix github-src
  doc/en/components/checkbox.md
  doc/en/components/radio.md
Labels: area: docs

#217 docs(ripple): add github-src
  doc/en/components/ripple.md
Labels: area: docs

#214 [JA] Latest changes up to 10/11
  doc/jp/components/grids/data-grid-accessibility.md
  doc/jp/components/grids/data-grid-cell-activation.md
  doc/jp/components/grids/data-grid-cell-editing.md
  doc/jp/components/grids/data-grid-cell-merging.md
  doc/jp/components/grids/data-grid-cell-selection.md
  doc/jp/components/grids/data-grid-column-animation.md
  doc/jp/components/grids/data-grid-column-chooser.md
  doc/jp/components/grids/data-grid-column-filtering.md
  doc/jp/components/grids/data-grid-column-moving.md
  doc/jp/components/grids/data-grid-column-options.md
  doc/jp/components/grids/data-grid-column-pinning.md
  doc/jp/components/grids/data-grid-column-resizing.md
  doc/jp/components/grids/data-grid-column-sorting.md
  doc/jp/components/grids/data-grid-column-summaries.md
  doc/jp/components/grids/data-grid-column-types.md
  doc/jp/components/grids/data-grid-horizontal-scrolling.md
  doc/jp/components/grids/data-grid-live-data.md
  doc/jp/components/grids/data-grid-load-save-layout.md
  doc/jp/components/grids/data-grid-local-data.md
  doc/jp/components/grids/data-grid-performance.md
  doc/jp/components/grids/data-grid-remote-data.md
  doc/jp/components/grids/data-grid-row-grouping.md
  doc/jp/components/grids/data-grid-row-highlighting.md
  doc/jp/components/grids/data-grid-row-paging.md
  doc/jp/components/grids/data-grid-row-pinning.md
  doc/jp/components/grids/data-grid-type-comparison-table.md
  doc/jp/components/grids/data-grid-type-heatmap-table.md
  doc/jp/components/grids/data-grid-type-matrix-table.md
  doc/jp/components/grids/data-grid-type-periodic-table.md
  doc/jp/components/grids/data-grid-type-sparkline-table.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grids.md
  doc/jp/components/grids/list.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/form.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/dock-manager-electron.md
  doc/jp/components/layouts/dock-manager-embedding-frames.md
  doc/jp/components/layouts/dock-manager-updating-panes.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/link-button.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#221 fix(topics): wrong sections order
  doc/en/components/avatar.md
  doc/en/components/badge.md
  doc/en/components/ripple.md
Labels: area: docs

#222 docs(navbar): replaced sample and updated text
  doc/en/components/menus/navbar.md
Labels: area: docs

#226 fix(dm): increase height of styling code view
  doc/en/components/layouts/dock-manager.md
Labels: status: verified

#220 [JA] Adding changes up to 12/11
  doc/jp/components/avatar.md
  doc/jp/components/badge.md
  doc/jp/components/calendar.md
  doc/jp/components/checkbox.md
  doc/jp/components/grids/data-grid-column-filtering.md
  doc/jp/components/grids/list.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/form.md
  doc/jp/components/layouts/card.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/radio.md
  doc/jp/components/ripple.md
  doc/jp/components/switch.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#225 mdd-21.2 feature-changelog-updates
  doc/en/components/general-changelog-dv.md
  doc/en/components/grids/data-grid-column-filtering.md
  doc/en/components/grids/data-grid-row-grouping.md
Labels: status: in-review

#227 Update general-changelog-dv.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#228 Checkbox doc and code snippets for Card
  doc/en/components/checkbox.md
  doc/en/components/layouts/card.md
Labels: status: in-review

#234 doc(form): move novalidate to separate snippet
  doc/en/components/inputs/form.md
Labels: area: docs, status: verified

#192 docs(icon): add topic
  doc/en/components/icon.md
  docfx/en/components/toc.json
Labels: area: docs

#197 docs(icon-button): add topic
  doc/en/components/inputs/icon-button.md
  docfx/en/components/toc.json
Labels: area: docs

#239 Code snippets for Avatar, Badge and List
  doc/en/components/avatar.md
  doc/en/components/badge.md
  doc/en/components/grids/list.md
Labels: status: in-review

#238 mdd-add-IGB-prefix
  doc/en/components/bullet-graph.md
  doc/en/components/charts/features/chart-performance.md
  doc/en/components/checkbox.md
  doc/en/components/editors/date-picker.md
  doc/en/components/editors/multi-column-combobox.md
  doc/en/components/general-changelog-dv.md
  doc/en/components/general-getting-started.md
  doc/en/components/geo-map-binding-data-csv.md
  doc/en/components/geo-map-binding-data-json-points.md
  doc/en/components/geo-map-binding-data-model.md
  doc/en/components/geo-map-binding-multiple-shapes.md
  doc/en/components/geo-map-binding-multiple-sources.md
  doc/en/components/geo-map-binding-shp-file.md
  doc/en/components/geo-map-display-esri-imagery.md
  doc/en/components/geo-map-display-osm-imagery.md
  doc/en/components/geo-map-type-scatter-area-series.md
  doc/en/components/geo-map-type-scatter-bubble-series.md
  doc/en/components/geo-map-type-scatter-contour-series.md
  doc/en/components/geo-map-type-scatter-density-series.md
  doc/en/components/geo-map-type-scatter-symbol-series.md
  doc/en/components/geo-map-type-shape-polygon-series.md
  doc/en/components/geo-map-type-shape-polyline-series.md
  doc/en/components/geo-map.md
  doc/en/components/grids/data-grid-accessibility.md
  doc/en/components/grids/data-grid-cell-editing.md
  doc/en/components/grids/data-grid-column-animation.md
  doc/en/components/grids/data-grid-column-chooser.md
  doc/en/components/grids/data-grid-column-filtering.md
  doc/en/components/grids/data-grid-column-moving.md
  doc/en/components/grids/data-grid-column-options.md
  doc/en/components/grids/data-grid-column-pinning.md
  doc/en/components/grids/data-grid-column-resizing.md
  doc/en/components/grids/data-grid-column-sorting.md
  doc/en/components/grids/data-grid-column-summaries.md
  doc/en/components/grids/data-grid-column-types.md
  doc/en/components/grids/data-grid-horizontal-scrolling.md
  doc/en/components/grids/data-grid-local-data.md
  doc/en/components/grids/data-grid-remote-data.md
  doc/en/components/grids/data-grid-row-grouping.md
  doc/en/components/grids/data-grid-row-highlighting.md
  doc/en/components/grids/data-grid-row-pinning.md
  doc/en/components/grids/data-grid-type-sparkline-table.md
  doc/en/components/grids/data-grid.md
  doc/en/components/linear-gauge.md
  doc/en/components/radial-gauge.md
  doc/en/components/spreadsheet-overview.md
  doc/en/components/zoomslider-overview.md
Labels: status: in-review

#235 fix minor typos in topics
  doc/en/components/checkbox.md
  doc/en/components/radio.md
  doc/en/components/switch.md
Labels: status: verified

#245 mdd-Build flag out Calendar (Blazor)
  doc/en/components/general-changelog-dv.md
  docfx/en/components/toc.json
Labels: status: in-review

#246 Fix the IFrame sizing of samples in docs
  doc/en/components/inputs/badge.md
  doc/en/components/inputs/button.md
  doc/en/components/inputs/ripple.md
  doc/en/components/layouts/avatar.md
  doc/en/components/layouts/card.md
Labels: status: in-review

#247 Revert "fixed API links in LOB topics"
  doc/en/components/general-cli-overview.md
  doc/en/components/grids/list.md
  doc/en/components/inputs/button.md
  doc/en/components/inputs/form.md
  doc/en/components/inputs/icon-button.md
  doc/en/components/inputs/ripple.md
  doc/en/components/layouts/avatar.md
  doc/en/components/layouts/card.md
  doc/en/components/layouts/dock-manager.md
  doc/en/components/layouts/icon.md
  doc/en/components/menus/navbar.md
  doc/en/components/menus/navigation-drawer.md
  doc/en/components/scheduling/calendar.md
Labels: area: lob
