Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-02, with the labels that each got.

#60 [JP] Updating topics with the latest changes.
  doc/jp/components/charts/chart-types-line.md
  doc/jp/components/charts/chart-types-pie.md
  doc/jp/components/dock-manager.md
  doc/jp/components/general-getting-started.md
Labels: area: localization, status: localized

#31 Adding the content for a new bar chart topic
  doc/en/components/charts/chart-types-bar.md
Labels: status: do not merge

#30 Adding the content for the new overview charts topic
  doc/en/components/charts/chart-type-overview.md
  doc/en/images/charts/ignite-ui-angular-category-chart-high-volume-data-1100.gif
  doc/en/images/charts/ignite-ui-angular-financial-chart-custom-tooltips-1100.jpg
  doc/en/images/charts/ignite-ui-angular-financial-chart-modular-design-1100.jpg
  doc/en/images/charts/ignite-ui-angular-financial-chart-smart-data-binding-1100.jpg
  doc/en/images/charts/ignite-ui-angular-financial-chart-trendlines-1100.jpg
  doc/en/images/charts/ignite-ui-angular-financial-chart-zooming-1100.gif
Labels: status: do not merge

#66 mdd-seo-descriptions
  doc/en/components/charts/chart-types-area.md
  doc/en/components/charts/chart-types-bar.md
  doc/en/components/charts/chart-types-column.md
  doc/en/components/charts/chart-types-donut.md
  doc/en/components/charts/chart-types-doughnut.md
  doc/en/components/charts/chart-types-financial.md
  doc/en/components/charts/chart-types-line.md
  doc/en/components/charts/chart-types-pie.md
  doc/en/components/charts/chart-types-polar.md
  doc/en/components/charts/chart-types-radial.md
  doc/en/components/charts/chart-types-scatter.md
  doc/en/components/charts/chart-types-spline.md
  doc/en/components/charts/chart-types-step.md
  doc/jp/components/charts/chart-types-doughnut.md
  docfx/en/components/toc.json
Labels: status: in-review
