Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-04, with the labels that each got.

#102 Mdd seo doc fixing
  doc/en/components/charts/types/bubble-chart.md
  doc/en/components/charts/types/donut-chart.md
  doc/en/components/charts/types/pie-chart.md
  doc/en/components/charts/types/spline-chart.md
  doc/en/components/charts/types/step-chart.md
  doc/en/components/charts/types/stock-chart.md
Labels: status: in-review

#103 mdd-seo-point-chart
  doc/en/components/charts/types/point-chart.md
  docfx/en/components/toc.json
Labels: status: in-review

#106 [JP] Updating the topics with the latest changes.
  doc/jp/components/charts/chart-overview.md
  doc/jp/components/charts/features/chart-animations.md
  doc/jp/components/charts/features/chart-annotations.md
  doc/jp/components/charts/features/chart-axis-gridlines.md
  doc/jp/components/charts/features/chart-axis-layouts.md
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/charts/features/chart-highlighting.md
  doc/jp/components/charts/features/chart-markers.md
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/charts/features/chart-synchronization.md
  doc/jp/components/charts/features/chart-tooltips.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/charts/types/area-chart.md
  doc/jp/components/charts/types/bar-chart.md
  doc/jp/components/charts/types/bubble-chart.md
  doc/jp/components/charts/types/column-chart.md
  doc/jp/components/charts/types/composite-chart.md
  doc/jp/components/charts/types/donut-chart.md
  doc/jp/components/charts/types/gantt-chart.md
  doc/jp/components/charts/types/line-chart.md
  doc/jp/components/charts/types/pie-chart.md
  doc/jp/components/charts/types/point-chart.md
  doc/jp/components/charts/types/radial-chart.md
  doc/jp/components/charts/types/scatter-chart.md
  doc/jp/components/charts/types/shape-chart.md
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/charts/types/spline-chart.md
  doc/jp/components/charts/types/stacked-chart.md
  doc/jp/components/charts/types/step-chart.md
  doc/jp/components/charts/types/stock-chart.md
  doc/jp/components/charts/types/treemap-chart.md
  doc/jp/components/charts/types/value-overlay-chart.md
  doc/jp/components/data-chart-series-types.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#110 mdd-seo-tooltip-templates
  doc/en/components/charts/features/chart-tooltips.md
Labels: status: in-review

#108 Add section for keyboard navigation and pane navigator #107
  doc/en/components/dock-manager.md
Labels: area: docs, status: verified

#114 Updating JP - vnext
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/chart-features.md
  doc/jp/components/charts/chart-overview.md
  doc/jp/components/charts/features/chart-animations.md
  doc/jp/components/charts/features/chart-annotations.md
  doc/jp/components/charts/features/chart-axis-gridlines.md
  doc/jp/components/charts/features/chart-axis-layouts.md
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/charts/features/chart-highlighting.md
  doc/jp/components/charts/features/chart-legends.md
  doc/jp/components/charts/features/chart-markers.md
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/charts/features/chart-overlays.md
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/charts/features/chart-synchronization.md
  doc/jp/components/charts/features/chart-titiles.md
  doc/jp/components/charts/features/chart-tooltips.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/charts/types/area-chart.md
  doc/jp/components/charts/types/bar-chart.md
  doc/jp/components/charts/types/bubble-chart.md
  doc/jp/components/charts/types/column-chart.md
  doc/jp/components/charts/types/composite-chart.md
  doc/jp/components/charts/types/donut-chart.md
  doc/jp/components/charts/types/gantt-chart.md
  doc/jp/components/charts/types/line-chart.md
  doc/jp/components/charts/types/network-chart.md
  doc/jp/components/charts/types/pie-chart.md
  doc/jp/components/charts/types/point-chart.md
  doc/jp/components/charts/types/polar-chart.md
  doc/jp/components/charts/types/pyramid-chart.md
  doc/jp/components/charts/types/radial-chart.md
  doc/jp/components/charts/types/scatter-chart.md
  doc/jp/components/charts/types/shape-chart.md
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/charts/types/spline-chart.md
  doc/jp/components/charts/types/stacked-chart.md
  doc/jp/components/charts/types/step-chart.md
  doc/jp/components/charts/types/stock-chart.md
  doc/jp/components/charts/types/treemap-chart.md
  doc/jp/components/charts/types/value-overlay-chart.md
  doc/jp/components/dock-manager.md
  doc/jp/components/financial-chart-custom-indicators.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#118 [JP] Updating with latest EN changes
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/chart-features.md
  doc/jp/components/charts/chart-overview.md
  doc/jp/components/charts/features/chart-animations.md
  doc/jp/components/charts/features/chart-annotations.md
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/charts/features/chart-highlighting.md
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/charts/features/chart-overlays.md
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/charts/types/area-chart.md
  doc/jp/components/charts/types/bar-chart.md
  doc/jp/components/charts/types/bubble-chart.md
  doc/jp/components/charts/types/composite-chart.md
  doc/jp/components/charts/types/gantt-chart.md
  doc/jp/components/charts/types/network-chart.md
  doc/jp/components/charts/types/pie-chart.md
  doc/jp/components/charts/types/point-chart.md
  doc/jp/components/charts/types/polar-chart.md
  doc/jp/components/charts/types/pyramid-chart.md
  doc/jp/components/charts/types/radial-chart.md
  doc/jp/components/charts/types/shape-chart.md
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/charts/types/treemap-chart.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#117 Update description in the floating pane section
  doc/en/components/dock-manager.md
Labels: area: docs

#122 [JP] Adding latest changes
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/charts/types/bubble-chart.md
  doc/jp/components/charts/types/polar-chart.md
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/charts/types/step-chart.md
  doc/jp/components/dock-manager.md
  doc/jp/components/geo-map-binding-data-model.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified
