Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-06, with the labels that each got.

#137 Updating JP - vnext
  doc/jp/components/general-changelog-dv.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#138 Fix the chart-performance topic
  doc/en/components/charts/features/chart-performance.md
Labels: status: in-review

#139 Remove all $PlatformShort$ for $Platform$
  doc/en/components/charts/features/chart-performance.md
  doc/en/components/charts/features/chart-tooltips.md
  doc/en/components/data-grid-cell-selection.md
  doc/en/components/dock-manager.md
Labels: status: in-review

#140 [JP] Updating Chart Performance topic.
  doc/jp/components/charts/features/chart-performance.md
Labels: area: localization, status: verified

#145 [JP] Fixes to match EN
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/geo-map-binding-multiple-sources.md
Labels: area: localization, status: verified

#144 Transform to SPA and add global search
  docfx/en/environment.json
  docfx/en/global.json
  docfx/en/index.md
  docfx/jp/environment.json
  docfx/jp/global.json
  docfx/jp/index.md
  docfx/kr/environment.json
  docfx/kr/global.json
  docfx/kr/index.md
  package.json
  yarn.lock
Labels: status: awaiting-test
