Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-12, with the labels that each got.

#249 refactor(radio): update styling example
  doc/en/components/inputs/radio.md
Labels: area: docs

#251 mdd-update-blazor-input-docs
  doc/en/components/grids/list.md
  doc/en/components/inputs/badge.md
  doc/en/components/inputs/button.md
  doc/en/components/inputs/checkbox.md
  doc/en/components/inputs/form.md
  doc/en/components/inputs/icon-button.md
  doc/en/components/inputs/radio.md
  doc/en/components/inputs/ripple.md
  doc/en/components/inputs/switch.md
  doc/en/components/layouts/avatar.md
  doc/en/components/layouts/card.md
  doc/en/components/layouts/icon.md
  doc/en/components/menus/navbar.md
  doc/en/components/menus/navigation-drawer.md
  doc/en/components/scheduling/calendar.md
Labels: status: in-review

#253 mdd-bug-fixing
  doc/en/components/editors/multi-column-combobox.md
  doc/en/components/grids/data-grid-cell-merging.md
  doc/en/components/grids/data-grid-column-options.md
  doc/en/components/grids/data-grid-column-pinning.md
  doc/en/components/grids/data-grid-horizontal-scrolling.md
Labels: status: in-review

#258 [JA] Adding changes up to 12/06
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/features/chart-synchronization.md
  doc/jp/components/charts/types/bar-chart.md
  doc/jp/components/editors/multi-column-combobox.md
  doc/jp/components/excel-library-working-with-charts.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/geo-map-binding-data-overview.md
  doc/jp/components/geo-map-binding-multiple-sources.md
  doc/jp/components/geo-map-resources-world-connections.md
  doc/jp/components/geo-map-resources-world-locations.md
  doc/jp/components/geo-map-resources-world-util.md
  doc/jp/components/geo-map-type-series.md
  doc/jp/components/grids/data-grid-cell-editing.md
  doc/jp/components/grids/data-grid-cell-merging.md
  doc/jp/components/grids/data-grid-column-options.md
  doc/jp/components/grids/data-grid-column-pinning.md
  doc/jp/components/grids/data-grid-column-types.md
  doc/jp/components/grids/data-grid-horizontal-scrolling.md
  doc/jp/components/grids/data-grid-local-data.md
  doc/jp/components/grids/data-grid-remote-data.md
  doc/jp/components/grids/data-grid-row-paging.md
  doc/jp/components/grids/grids.md
  doc/jp/components/grids/list.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/form.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/ripple.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/scheduling/calendar.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#255 docs(input): add topic - vNext
  doc/en/components/general-changelog-dv.md
  doc/en/components/inputs/input.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#262 [JA] Fixing Icon-Button topic.
  doc/jp/components/inputs/icon-button.md
Labels: status: awaiting-test

#263 mdd-bug-fixes
  doc/en/components/grids/data-grid-row-grouping.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: in-review

#267 [JA] Adding changes up to 10/12
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/data-grid-row-grouping.md
  doc/jp/components/inputs/input.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#259 Fixes for docs in 21.2
  doc/en/components/editors/date-picker.md
  doc/en/components/editors/multi-column-combobox.md
  doc/en/components/inputs/form.md
Labels: status: in-review

#261 SEO updates for WC and Blazor docs
  doc/en/components/inputs/button.md
  doc/en/components/inputs/checkbox.md
  doc/en/components/inputs/form.md
  doc/en/components/layouts/icon.md
Labels: status: in-development

#268 Update data-grid-column-filtering.md
  doc/en/components/grids/data-grid-column-filtering.md
Labels: status: in-review

#269 Update data-grid-column-filtering.md
  doc/en/components/grids/data-grid-column-filtering.md
Labels: status: in-review

#271 [JA] Adding latest changes and localization fixes
  doc/jp/components/editors/date-picker.md
  doc/jp/components/editors/multi-column-combobox.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/geo-map-binding-data-csv.md
  doc/jp/components/grids/data-grid-column-filtering.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/form.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/scheduling/calendar.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#273 Update data-grid-cell-merging.md
  doc/en/components/grids/data-grid-cell-merging.md
Labels: status: in-review

#275 [JA] Latest updates
  doc/jp/components/charts/features/chart-titles.md
  doc/jp/components/editors/date-picker.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/data-grid-column-filtering.md
Labels: area: localization, status: localized, status: verified

#276 [JA] Getting Started topic localization
  doc/jp/components/general-getting-started.md
Labels: status: verified

#282 fix(DockManager): Fixed an api link
  doc/en/components/layouts/dock-manager.md
Labels: area: api, status: verified
