Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2021-09, with the labels that each got.

#161 mdd-cell-merging
  doc/en/components/data-grid-cell-merging.md
  docfx/en/components/toc.json
Labels: status: in-review

#160 Create data-grid-load-save-layout.md
  doc/en/components/data-grid-load-save-layout.md
  docfx/en/components/toc.json
Labels: status: in-review

#162 [JP] Adding latest changes
  doc/jp/components/data-grid-cell-merging.md
  doc/jp/components/data-grid-load-save-layout.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#159 feat(dock-manager): add styling topic
  doc/en/components/dock-manager.md
Labels: area: docs, status: do not merge, status: verified

#164 feat(dock-manager): add styling topic
  doc/en/components/dock-manager.md
Labels: area: docs

#165 [JA] Adding latest changes
  doc/jp/components/dock-manager.md
  doc/jp/components/spreadsheet-overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#166 mdd-update-docs-21.2
  doc/en/components/data-grid-cell-merging.md
  doc/en/components/data-grid-load-save-layout.md
Labels: status: in-review
