Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-03, with the labels that each got.

#304 feat(dockmanager): add info about new props
  doc/en/components/layouts/dock-manager.md
Labels: area: docs, status: verified

#306 Update data-grid.md
  doc/en/components/grids/data-grid.md
Labels: status: in-review

#308 [JA] Updating Dock Manager
  doc/jp/components/layouts/dock-manager.md
Labels: area: localization, status: localized, status: verified

#316 [JA] Adding changes up to 11/03
  doc/jp/components/general-getting-started.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/list.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/form.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/ripple.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/scheduling/calendar.md
Labels: area: localization, status: localized, status: verified

#320 feat(chip): add chip docs
  doc/en/components/inputs/chip.md
  docConfig.json
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#319 didimmova/toast docs
  doc/en/components/notifications/toast.md
  docConfig.json
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#323 Update general-changelog-dv.md
  doc/en/components/general-changelog-dv.md
  doc/en/components/grids/data-grid-cell-merging.md
  doc/en/components/grids/data-grid-column-filtering.md
Labels: status: in-development

#326 Update date-picker.md
  doc/en/components/editors/date-picker.md
Labels: status: in-review

#324 Update general-changelog-dv.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#329 [JA] Updating with changes up to 24/03
  doc/jp/components/editors/date-picker.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/grids/data-grid-column-filtering.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/layouts/dock-manager-electron.md
  doc/jp/components/notifications/snackbar.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/zoomslider-overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#328 Add Dropdown topic
  doc/en/components/inputs/dropdown.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified
