Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-08, with the labels that each got.

#426 [JA] Adding changes up to 28/07
  doc/jp/components/grids/list.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/circular-progress.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/inputs/form.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/linear-progress.md
  doc/jp/components/inputs/mask-input.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/rating.md
  doc/jp/components/inputs/ripple.md
  doc/jp/components/inputs/select.md
  doc/jp/components/inputs/slider.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/layouts/accordion.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/layouts/tabs.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/notifications/snackbar.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/scheduling/calendar.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: in-test

#424 remove child dependencies from defineComponents
  doc/en/components/grids/list.md
  doc/en/components/grids/tree.md
  doc/en/components/inputs/dropdown.md
  doc/en/components/inputs/rating.md
  doc/en/components/inputs/select.md
  doc/en/components/layouts/accordion.md
  doc/en/components/layouts/card.md
  doc/en/components/menus/navigation-drawer.md
  doc/jp/components/grids/list.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/layouts/card.md
  doc/jp/components/menus/navigation-drawer.md
  doc/kr/components/grids/list.md
  doc/kr/components/menus/navigation-drawer.md
Labels: status: verified

#427 [JA] Minor changes as per EN
  doc/jp/components/inputs/rating.md
  doc/jp/components/inputs/select.md
  doc/jp/components/layouts/accordion.md
Labels: area: localization, status: localized, status: verified
