Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-11, with the labels that each got.

#555 Update code snippets of display density topic to be like in the sample
  doc/en/components/grids/_shared/display-density.md
Labels: status: in-review

#558 mdd-22.2 changelog updates
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#556 updated few topics
  doc/en/components/grids/_shared/export-excel.md
  doc/en/components/grids/_shared/live-data.md
  doc/en/components/grids/_shared/validation.md
Labels: status: in-development

#568 mdd-tree-grid-overview
  doc/en/components/grids/tree-grid/overview.md
Labels: status: in-review

#570 WC Grid Overview snippets
  doc/en/components/grids/grid/overview.md
Labels: status: in-review

#573 adding grid overview topic to WC toc
  docfx/en/components/toc.json
Labels: status: in-review

#574 mdd update new grid landing page and TOC
  doc/en/components/grids/grids-header.md
  docfx/en/components/toc.json
Labels: status: in-review

#571 Hide child pages for Tree-Grid (Blazor)
  docfx/en/components/toc.json
Labels: status: in-development

#577 Update groupby.md
  doc/en/components/grids/grid/groupby.md
Labels: status: in-review

#579 [JP] Build fixes.
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/tree-grid/overview.md
Labels: area: localization, status: in-test

#580 [JP] Grid topics localization fixes.
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/batch-editing.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sizing.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/_shared/virtualization.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/grids/tree-grid/overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: verified

#582 Update toc.json
  docfx/en/components/toc.json
Labels: status: in-review

#583 [JP] Fixing links, other minor changes.
  doc/jp/components/charts/features/chart-data-aggregations.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/sizing.md
  doc/jp/components/grids/grid/overview.md
  doc/jp/components/grids/grids-header.md
  doc/jp/components/grids/tree-grid/overview.md
  doc/jp/components/layouts/accordion.md
  docfx/jp/components/toc.json
Labels: area: localization, status: verified

#587 wc snippets
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/batch-editing.md
  doc/en/components/grids/_shared/cell-editing.md
  doc/en/components/grids/_shared/collapsible-column-groups.md
  doc/en/components/grids/_shared/column-hiding.md
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/_shared/column-resizing.md
  doc/en/components/grids/_shared/column-types.md
  doc/en/components/grids/_shared/conditional-cell-styling.md
  doc/en/components/grids/_shared/display-density.md
  doc/en/components/grids/_shared/editing.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/filtering.md
  doc/en/components/grids/_shared/keyboard-navigation.md
  doc/en/components/grids/_shared/live-data.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/multi-row-layout.md
  doc/en/components/grids/_shared/paging.md
  doc/en/components/grids/_shared/row-actions.md
  doc/en/components/grids/_shared/row-adding.md
  doc/en/components/grids/_shared/row-drag.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/_shared/row-pinning.md
  doc/en/components/grids/_shared/row-selection.md
  doc/en/components/grids/_shared/search.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/state-persistence.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/_shared/template.md
  doc/en/components/grids/_shared/toolbar.md
  doc/en/components/grids/_shared/validation.md
  doc/en/components/grids/grid/groupby.md
Labels: status: in-review

#590 Updating JP - link fixes, WC snippets.
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/batch-editing.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/clipboard-interactions.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sizing.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/template.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/_shared/virtualization.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/overview.md
  doc/jp/components/grids/grid/paste-excel.md
  doc/jp/components/grids/grid/selection-based-aggregates.md
  doc/jp/components/layouts/accordion.md
Labels: area: localization, status: verified

#595 [Localization] Updating JP for #591, #592 and #593
  doc/jp/components/grids/_shared/batch-editing.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/grid/overview.md
  doc/jp/components/inputs/input.md
  docfx/jp/components/toc.json
Labels: area: localization, status: in-test

#604 [JA] Latest localization changes
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-getting-started-blazor-maui.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/overview.md
  doc/jp/components/grids/grids.md
  doc/jp/components/grids/tree-grid/overview.md
  doc/jp/components/layouts/tabs.md
Labels: area: localization, status: localized, status: verified
