Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-01, with the labels that each got.

#286 feat(dockmanager): add section for adding content at runtime
  doc/en/components/layouts/dock-manager.md
Labels: area: docs, status: verified

#288 [JA] Latest changes
  doc/jp/components/layouts/dock-manager.md
Labels: area: localization, status: localized, status: verified

#285 Update data-grid-column-filtering.md
  doc/en/components/grids/data-grid-column-filtering.md
Labels: status: in-review

#289 mdd-add-axis-modes-&-scale
  doc/en/components/charts/features/chart-axis-options.md
Labels: status: in-review

#291 [JA] Adding changes up to 20/01
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/grids/data-grid-column-filtering.md
Labels: area: localization, status: localized, status: verified

#266 Add framework buttons
  package.json
  yarn.lock
Labels: status: awaiting-test

#294 chore(*): Updated Changelog topic with 2.0 changes
  doc/en/components/general-changelog-dv.md
Labels: area: docs
