Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-05, with the labels that each got.

#359 [JA] Updating with latest changes
  doc/jp/components/charts/features/chart-annotations.md
  doc/jp/components/charts/features/chart-axis-layouts.md
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started-blazor-client.md
  doc/jp/components/general-getting-started-blazor-maui.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/general-installing-blazor.md
  doc/jp/components/general-nuget-feed.md
  doc/jp/components/grids/data-grid-row-grouping.md
  doc/jp/images/general/getting-started-blazor-card-windows.jpg
  doc/jp/images/general/getting-started-blazor-card.jpg
  doc/jp/images/general/new-blazor-project-client.jpg
  doc/jp/images/general/new-blazor-project-configure-client.jpg
  doc/jp/images/general/new-blazor-project-configure-maui.jpg
  doc/jp/images/general/new-blazor-project-configure-server.jpg
  doc/jp/images/general/new-blazor-project-info-client.jpg
  doc/jp/images/general/new-blazor-project-info-server.jpg
  doc/jp/images/general/new-blazor-project-maui.jpg
  doc/jp/images/general/new-blazor-project-name.jpg
  doc/jp/images/general/new-blazor-project-server.jpg
  doc/jp/images/general/new-blazor-project-template.jpg
  doc/jp/images/general/new-blazor-project.jpg
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#358 Mdd pager
  doc/en/components/grids/data-grid-row-paging.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: in-review

#361 mdd-localization
  doc/en/components/grids/data-grid-localization.md
  docfx/en/components/toc.json
Labels: status: in-review

#365 Update general-changelog-dv.md (Callout Corner Radius for all annotations)
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#366 Update general-changelog-dv.md (AssigningCategoryStyle for all series)
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#368 mdd-update-toc-for-22.1
  docfx/en/components/toc.json
Labels: status: in-review

#301 Add Tree topic
  doc/en/components/grids/tree.md
  docfx/en/components/toc.json
Labels: status: awaiting-test
