Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-04, with the labels that each got.

#330 [JA] Adding Dropdown
  doc/jp/components/inputs/dropdown.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#325 feat(docs): add basic theming docs
  doc/en/components/themes/overview.md
  docfx/en/components/toc.json
Labels: area: docs, status: resolved

#331 Update for SR
  doc/en/components/general-changelog-dv.md
  doc/en/components/themes/overview.md
  docConfig.json
Labels: status: in-review

#332 [JA] Adding Themes - Overview
  doc/jp/components/themes/overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#309 Add Progress Components topics
  doc/en/components/inputs/circular-progress.md
  doc/en/components/inputs/linear-progress.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#335 mdd-Fix changelog
  doc/en/components/general-changelog-dv.md
Labels: status: in-development

#338 [JA] Adding Circular and Linear Progress
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/inputs/circular-progress.md
  doc/jp/components/inputs/linear-progress.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#339 renamed drop down to dropdown
  doc/en/components/inputs/dropdown.md
  doc/jp/components/inputs/dropdown.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#342 mdd-273657
  doc/en/components/grids/data-grid-column-filtering.md
Labels: status: in-review

#348 [JA] Adding changes up to 23/04
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/grids/data-grid-column-filtering.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/circular-progress.md
  doc/jp/components/inputs/linear-progress.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/notifications/snackbar.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/themes/overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified
