Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-10, with the labels that each got.

#485 Port state topic from angular
  doc/en/components/grids/_shared/state-persistence.md
  docfx/en/components/toc.json
Labels: status: in-review

#484 Port grids summaries topic from angular docs
  doc/en/components/grids/_shared/summaries.md
  docfx/en/components/toc.json
Labels: status: in-review

#471 Port display density topic from angular docs
  doc/en/components/grids/_shared/display-density.md
  docfx/en/components/toc.json
Labels: status: in-review

#492 docs(editing): Port cell editing topic
  doc/en/components/grids/_shared/cell-editing.md
  docfx/en/components/toc.json
Labels: status: in-development

#519 refactor(themes): update topics and add new guides
  doc/en/components/grids/list.md
  doc/en/components/inputs/radio.md
  doc/en/components/themes/component-themes.md
  doc/en/components/themes/configuration.md
  doc/en/components/themes/elevations.md
  doc/en/components/themes/overview.md
  doc/en/components/themes/palettes.md
  doc/en/components/themes/typography.md
  doc/en/images/avatar-markup.png
  doc/jp/components/grids/list.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/themes/elevations.md
  doc/jp/components/themes/palettes.md
  doc/jp/components/themes/typography.md
  doc/kr/components/grids/list.md
  docfx/en/components/toc.json
Labels: area: docs, status: awaiting-test, topic: themes

#517 docs: Add theming topic
  doc/en/components/grids/theming.md
  docfx/en/components/toc.json
Labels: area: docs, topic: grids, status: awaiting-test

#483 Port grids sorting topic from angular
  doc/en/components/grids/_shared/sorting.md
  docfx/en/components/toc.json
Labels: status: in-review

#482 Port excel style filtering topic from angular docs
  doc/en/components/grids/_shared/excel-style-filtering.md
  docfx/en/components/toc.json
Labels: status: in-review

#479 Port conditional styling topic from angular docs
  doc/en/components/grids/_shared/conditional-cell-styling.md
  docfx/en/components/toc.json
Labels: status: in-review

#474 Port row pinning topic from angular docs.
  doc/en/components/grids/_shared/row-pinning.md
  docfx/en/components/toc.json
Labels: status: in-review

#470 Port column-moving topic from angular docs.
  doc/en/components/grids/_shared/column-moving.md
  docfx/en/components/toc.json
Labels: status: in-review

#464 Port column-hiding topic from angular docs.
  doc/en/components/grids/_shared/column-hiding.md
  docfx/en/components/toc.json
Labels: status: in-review

#476 Port row selection topic from angular docs.
  doc/en/components/grids/_shared/row-selection.md
  docfx/en/components/toc.json
Labels: status: in-development

#465 Port paste-excel selection-based-aggregates
  doc/en/components/grids/lob-grid/paste-excel.md
  doc/en/components/grids/lob-grid/selection-based-aggregates.md
Labels: status: in-development

#467 Port Multi Row Layout and Remote Data Operations topics
  doc/en/components/grids/_shared/multi-row-layout.md
  doc/en/components/grids/_shared/remote-data-operations.md
  docfx/en/components/toc.json
Labels: status: in-development

#458 Port grid.md
  doc/en/components/grids/lob-grid/overview.md
  doc/en/images/general/landing-grid-page.PNG
Labels: status: in-development

#472 Port Grid Sizing topic from angular docs.
  doc/en/components/grids/_shared/sizing.md
  doc/en/images/grid_sizing/columns-150px-empty-area-v2.jpg
  doc/en/images/grid_sizing/columns-150px-extra-area-v2.jpg
  doc/en/images/grid_sizing/columns-default-all-first-100px-v2.jpg
  doc/en/images/grid_sizing/columns-default-all-min-136px-v2.jpg
  doc/en/images/grid_sizing/columns-default-all-row-selectors-v2.jpg
  doc/en/images/grid_sizing/columns-default-first-rest-100px-v2.jpg
  doc/en/images/grid_sizing/columns-default-first-rest-300px-v2.jpg
  doc/en/images/grid_sizing/columns-default-gridWidth-null-v2.jpg
  doc/en/images/grid_sizing/columns-percent-100p-v2.jpg
  doc/en/images/grid_sizing/columns-percent-bigger-100p-v2.jpg
  doc/en/images/grid_sizing/columns-percent-gridWidth-null-v2.jpg
  doc/en/images/grid_sizing/columns-percent-less-100p-v2.jpg
  doc/en/images/grid_sizing/height-500px-14rows-v2.jpg
  doc/en/images/grid_sizing/height-500px-4rows-v2.jpg
  doc/en/images/grid_sizing/height-700px-14rows-parent-noscroll-v2.jpg
  doc/en/images/grid_sizing/height-700px-14rows-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/height-null-14rows-v2.jpg
  doc/en/images/grid_sizing/height-null-24row-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/height-null-24rows-parent-noscroll-v2.jpg
  doc/en/images/grid_sizing/height-null-24rows-parent-noscroll.jpg
  doc/en/images/grid_sizing/height-null-24rows-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/height-null-24rows-v2.jpg
  doc/en/images/grid_sizing/height-percent-100-parent-100-v2.jpg
  doc/en/images/grid_sizing/height-percent-100-parent-800px-v2.jpg
  doc/en/images/grid_sizing/height-percent-130p-parent-noscroll-v2.jpg
  doc/en/images/grid_sizing/height-percent-130p-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/height-undefined-14rows-v2.jpg
  doc/en/images/grid_sizing/height-undefined-7rows-v2.jpg
  doc/en/images/grid_sizing/hgrid-height-percentages-v2.jpg
  doc/en/images/grid_sizing/hgrid-width-percentages-v2.jpg
  doc/en/images/grid_sizing/width-cols-scroll-parent-noscroll-v2.jpg
  doc/en/images/grid_sizing/width-cols-scroll-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/width-cols-scrollbar-v2.jpg
  doc/en/images/grid_sizing/width-null-no-scroll-v2.jpg
  doc/en/images/grid_sizing/width-null-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/width-null-scroll-v2.jpg
  doc/en/images/grid_sizing/width-percent-100p-v2.jpg
  doc/en/images/grid_sizing/width-percent-150p-parent-noscroll-v2.jpg
  doc/en/images/grid_sizing/width-percent-150p-parent-scroll-v2.jpg
  doc/en/images/grid_sizing/width-percent-parent-100p-v2.jpg
  docfx/en/components/toc.json
Labels: status: in-development

#486 Port column resizing topic from angular docs.
  doc/en/components/grids/_shared/column-resizing.md
  docfx/en/components/toc.json
Labels: status: in-development

#488 Port column pinning topic from angular docs.
  doc/en/components/grids/_shared/column-pinning.md
  docfx/en/components/toc.json
Labels: status: in-development

#491 docs(grid-editing): port batch-editing topic
  doc/en/components/grids/_shared/batch-editing.md
  docfx/en/components/toc.json
Labels: status: in-development

#539 Changes to topics : state persistence, summaries, sorting, ESF, conditional styling
  doc/en/components/grids/_shared/conditional-cell-styling.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/summaries.md
  docfx/en/components/toc.json
Labels: status: in-review
