Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-07, with the labels that each got.

#386 Update seo cta banners
  doc/en/images/marketing/ignite-ui-for-blazor.gif
  doc/en/images/marketing/ignite-ui-for-react.gif
  doc/jp/images/marketing/ignite-ui-for-blazor.gif
  doc/jp/images/marketing/ignite-ui-for-react.gif
  package.json
  yarn.lock
Labels: area: seo, status: awaiting-test

#418 [Localization] Adding the latest topic changes, fixes.
  doc/jp/components/charts/chart-overview.md
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/charts/types/gantt-chart.md
  doc/jp/components/charts/types/line-chart.md
  doc/jp/components/charts/types/polar-chart.md
  doc/jp/components/excel-library-using-cells.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/geo-map-display-bing-imagery.md
  doc/jp/components/grids/data-grid-column-pinning.md
  doc/jp/components/grids/grids.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/themes/elevations.md
Labels: area: localization, status: localized, status: verified

#410 Add Tabs topic
  doc/en/components/layouts/tabs.md
  docfx/en/components/toc.json
Labels: area: docs, status: awaiting-test

#411 Add Accordion Topic
  doc/en/components/layouts/accordion.md
  docfx/en/components/toc.json
Labels: area: docs, status: awaiting-test

#357 feat(rating): add rating docs
  doc/en/components/inputs/rating.md
  docfx/en/components/toc.json
Labels: area: docs, status: do not merge, rating

#401 Add mask input topic
  doc/en/components/inputs/mask-input.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#407 docs(select): provide select component documentation
  doc/en/components/inputs/select.md
  docfx/en/components/toc.json
Labels: status: awaiting-test, select

#420 docs(date-time-input): Update date-time-input.md
  doc/en/components/inputs/date-time-input.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#421 refactor(rating): update to reflect latest version changes
  doc/en/components/inputs/rating.md
Labels: area: docs, rating

#423 Mdd inputs
  doc/en/components/grids/tree.md
  doc/en/components/inputs/badge.md
  doc/en/components/inputs/button.md
  doc/en/components/inputs/checkbox.md
  doc/en/components/inputs/chip.md
  doc/en/components/inputs/circular-progress.md
  doc/en/components/inputs/date-time-input.md
  doc/en/components/inputs/dropdown.md
  doc/en/components/inputs/form.md
  doc/en/components/inputs/icon-button.md
  doc/en/components/inputs/input.md
  doc/en/components/inputs/linear-progress.md
  doc/en/components/inputs/mask-input.md
  doc/en/components/inputs/radio.md
  doc/en/components/inputs/rating.md
  doc/en/components/inputs/ripple.md
  doc/en/components/inputs/select.md
  doc/en/components/inputs/slider.md
  doc/en/components/inputs/switch.md
  docfx/en/components/toc.json
Labels: status: in-review
