Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-12, with the labels that each got.

#608 docs(pivot): port overview topic
  doc/en/components/grids/pivot-grid/overview.md
  docfx/en/components/toc.json
Labels: status: in-review

#614 modify getting-started.md with info on webcomponents
  doc/en/components/general-getting-started.md
Labels: status: awaiting-test

#622 [JP] Pivot Grid overview fix.
  doc/jp/components/grids/pivot-grid/overview.md
Labels: area: localization, status: verified

#627 [JA] Updating changelog topics
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/pivot-grid/overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#605 Edit tree grid and grid overview topics
  doc/en/components/grids/grid/overview.md
  doc/en/components/grids/tree-grid/overview.md
  docfx/en/components/toc.json
Labels: topic: grids, status: awaiting-test

#615 Add Stepper topic
  doc/en/components/layouts/stepper.md
  doc/en/images/stepper/stepper-contentTop.png
  doc/en/images/stepper/stepper-step.png
  docfx/en/components/toc.json
Labels: area: docs

#616 feat(combo): provide component documentation
  doc/en/components/grids/combo/features.md
  doc/en/components/grids/combo/overview.md
  doc/en/components/grids/combo/templates.md
  docfx/en/components/toc.json
Labels: status: verified, combo

#632 [JP] Adding the latest localization changes.
  doc/jp/components/grids/combo/features.md
  doc/jp/components/grids/combo/overview.md
  doc/jp/components/grids/combo/templates.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/grids/grid/overview.md
  doc/jp/components/grids/grid/paste-excel.md
  doc/jp/components/grids/grid/selection-based-aggregates.md
  doc/jp/components/grids/pivot-grid/overview.md
  doc/jp/components/grids/tree-grid/overview.md
  doc/jp/components/inputs/mask-input.md
  doc/jp/components/layouts/accordion.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/layouts/tabs.md
  doc/jp/images/stepper/stepper-contentTop.png
  doc/jp/images/stepper/stepper-step.png
  docfx/jp/components/toc.json
Labels: area: localization, status: verified

#633 [JP] Stepper samples fixes
  doc/jp/components/layouts/stepper.md
Labels: area: localization
