Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-06, with the labels that each got.

#371 Update toc.json for Calendar
  docfx/en/components/toc.json
Labels: status: in-review

#369 [JA] Updating with changes up to 29/05
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/data-grid-localization.md
  doc/jp/components/grids/data-grid-row-paging.md
  doc/jp/components/grids/tree.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#373 mdd-update-dockmanager
  doc/en/components/layouts/dock-manager.md
  docConfig.json
  docfx/en/components/toc.json
Labels: status: in-review

#375 Blazor api links and versioning
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#355 Add Expansion Panel topic
  doc/en/components/layouts/expansion-panel.md
  docfx/en/components/toc.json
Labels: status: resolved

#377 Update general-changelog-dv.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#380 Mdd misc4 22.1
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#379 Update grids.md
  doc/en/components/grids/grids.md
Labels: status: in-review

#378 Update general-changelog-dv.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#385 [JA] Localization fixes
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grids.md
  doc/jp/components/grids/list.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/circular-progress.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/inputs/form.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/linear-progress.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/ripple.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/notifications/snackbar.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/scheduling/calendar.md
  docfx/jp/components/toc.json
Labels: status: localized, status: in-test, status: verified

#384 Update data-grid-localization.md
  doc/en/components/grids/data-grid-localization.md
Labels: status: in-review

#389 Update toc.json
  docfx/en/components/toc.json
Labels: status: in-review

#390 Update dock-manager.md
  doc/en/components/layouts/dock-manager.md
Labels: status: in-review

#391 Add Binding samples Blazor (Input and MCC)
  doc/en/components/editors/multi-column-combobox.md
  doc/en/components/inputs/input.md
Labels: status: in-review

#392 mdd-update-for-tree
  doc/en/components/grids/tree.md
  docfx/en/components/toc.json
Labels: status: in-review

#395 mdd-add data tooltips section
  doc/en/components/charts/features/chart-tooltips.md
  doc/kr/components/charts/features/chart-tooltips.md
Labels: status: in-review

#396 [JA] Latest updates
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-tooltips.md
  doc/jp/components/editors/multi-column-combobox.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/data-grid-localization.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/input.md
  doc/jp/components/layouts/dock-manager.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#397 Mdd 274304
  doc/en/components/charts/types/column-chart.md
Labels: status: in-review

#402 [JP] Adding the latest documentation changes - charts, changelog.
  doc/jp/components/charts/features/chart-legends.md
  doc/jp/components/charts/types/column-chart.md
  doc/jp/components/charts/types/line-chart.md
  doc/jp/components/general-changelog-dv.md
Labels: status: localized, status: verified

#403 [JP] Dock Manager topic updates
  doc/jp/components/layouts/dock-manager.md
Labels: status: localized, status: verified

#356 Add date-time-input.md
  doc/en/components/inputs/date-time-input.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified

#394 docs(styling): provide theming documentation
  doc/en/components/themes/elevations.md
  doc/en/components/themes/palettes.md
  doc/en/components/themes/typography.md
  docfx/en/components/toc.json
Labels: area: docs, status: verified, topic: themes
