Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2022-09, with the labels that each got.

#441 [JA] Adding changes up to 08/09
  doc/jp/components/general-getting-started-blazor-client.md
  doc/jp/components/general-getting-started-blazor-maui.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/geo-map-display-heat-imagery.md
Labels: area: localization, status: localized, status: verified

#450 [JA] Adding LOB grid topics
  doc/jp/components/lob/grid/overview.md
  doc/jp/components/lob/hierarchical-grid/overview.md
  doc/jp/components/lob/pivot-grid/overview.md
  doc/jp/components/lob/templates/NOTE.txt
  doc/jp/components/lob/tree-grid/overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#453 Update general-getting-started.md
  doc/en/components/general-getting-started.md
Labels: status: in-review

#451 Add new blazor topics
  doc/en/components/blazor-excel-library-temporarily-stop-automatic-calculation-of-formulas-to-speed-up-processing.md
  doc/en/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md
  doc/en/components/customize-marker-display-in-blazor-charts.md
  doc/en/images/general/blazor-excel.png
  doc/en/images/general/blazor-wasm-app-2.png
  doc/en/images/general/blazor-wasm-app.png
  doc/en/images/general/lazy-loaded-assembly.png
  doc/en/images/general/lazy-loading-of-assembly.png
  doc/jp/components/blazor-excel-library-temporarily-stop-automatic-calculation-of-formulas-to-speed-up-processing.md
  doc/jp/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md
  doc/jp/components/customize-marker-display-in-blazor-charts.md
  doc/jp/images/general/blazor-excel.png
  doc/jp/images/general/blazor-wasm-app-2.png
  doc/jp/images/general/blazor-wasm-app.png
  doc/jp/images/general/lazy-loaded-assembly.png
  doc/jp/images/general/lazy-loading-of-assembly.png
  doc/kr/components/blazor-excel-library-temporarily-stop-automatic-calculation-of-formulas-to-speed-up-processing.md
  doc/kr/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md
  doc/kr/components/customize-marker-display-in-blazor-charts.md
  doc/kr/images/general/blazor-excel.png
  doc/kr/images/general/blazor-wasm-app-2.png
  doc/kr/images/general/blazor-wasm-app.png
  doc/kr/images/general/lazy-loaded-assembly.png
  doc/kr/images/general/lazy-loading-of-assembly.png
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: translating, status: in-test

#457 [JA] Updating with changes up to 22/09
  doc/jp/components/charts/features/chart-axis-gridlines.md
  doc/jp/components/charts/features/chart-axis-layouts.md
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/grids/_shared/template.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/inputs/rating.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#428 Add dialog topic
  doc/en/components/notifications/dialog.md
  docfx/en/components/toc.json
Labels: status: verified
