Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-05, with the labels that each got.

#804 [JA] Updating with changes up to 25 April '23
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/geo-map-binding-data-model.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/layouts/stepper.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#814 mdd-fix-grids-broken-links
  doc/en/components/grids/_shared/column-types.md
  doc/en/components/grids/_shared/editing.md
  doc/en/components/grids/_shared/paging.md
  doc/en/components/grids/data-grid.md
  doc/en/components/grids/grids-header.md
Labels: status: in-review

#815 improve dialog Blazor code snippet
  doc/en/components/notifications/dialog.md
  doc/jp/components/notifications/dialog.md
Labels: status: verified

#818 Update theming.md
  doc/en/components/grids/data-grid/theming.md
Labels: status: in-review

#823 Remove custom row-actions.md
  doc/en/components/grids/_shared/row-actions.md
Labels: status: in-review

#798 Add column selection styling section.
  doc/en/components/grids/_shared/column-selection.md
Labels: status: verified

#780 Grid Overview - update code snippets and some incorrect sections.
  doc/en/components/grids/data-grid.md
Labels: status: verified

#794 Add grid master detail topic with snippets
  doc/en/components/grids/grid/master-detail.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: do not merge, status: blocked, status: verified

#802 Grid Column Types - Fix WC/Blazor grid snippets and sections.
  doc/en/components/grids/_shared/column-types.md
Labels: status: verified

#836 [JA] Adding changes up to 25 May
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grid/master-detail.md
  docfx/jp/components/toc.json
Labels: status: localized
