Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-02, with the labels that each got.

#561 chore(*): package updates and node 16 and 18 update
  .github/workflows/build-blazor.yml
  .github/workflows/build-react.yml
  README.md
  doc/en/components/grids/_shared/virtualization.md
  doc/jp/components/grids/_shared/virtualization.md
  package-lock.json
  package.json
  src/ext/MarkdownTransformer.ts
  tsconfig.json
  yarn.lock
Labels: status: do not merge, area: ci

#677 [JA] Changes to match EN docs
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/inputs/date-time-input.md
Labels: area: localization, status: localized, status: verified

#680 [JA] Fixing notes
  doc/jp/components/charts/features/chart-data-aggregations.md
  doc/jp/components/charts/features/chart-performance.md
  doc/jp/components/general-licensing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/layouts/accordion.md
Labels: area: localization, status: localized

#690 [JA] Fixing broken button link
  doc/jp/components/inputs/button.md
Labels: area: localization
