Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-06, with the labels that each got.

#844 Add beta and preview labels support
  package-lock.json
  package.json
  src/ext/MarkdownTransformer.ts
  yarn.lock
Labels: status: awaiting-test

#847 mdd-toolbar-topic
  doc/en/components/menus/toolbar.md
  doc/en/images/toolbar_icons.png
  docConfig.json
  docfx/en/components/toc.json
Labels: status: in-review

#849 [JA] Latest changes. Adding Toolbar
  doc/jp/components/charts/features/chart-axis-types.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/menus/toolbar.md
  doc/jp/images/toolbar_icons.png
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#813 Grid paging- minor fixes.
  doc/en/components/grids/_shared/paging.md
Labels: bug: in-product

#850 dialog - update code snippets
  doc/en/components/notifications/dialog.md
  doc/jp/components/notifications/dialog.md
Labels: status: verified

#807 Add ESF styling section
  doc/en/components/grids/_shared/excel-style-filtering.md
Labels: status: do not merge

#796 Rearrange Collapsible Groups topic, update WC and Blazor code snippets.
  doc/en/components/grids/_shared/collapsible-column-groups.md
Labels: status: do not merge, status: awaiting-test

#830 Add update layout section
  doc/en/components/layouts/dock-manager.md
Labels: status: awaiting-test

#819 Update Row Adding topic with code snippets and other small fixes.
  doc/en/components/grids/_shared/row-adding.md
Labels: status: do not merge

#795 Update cell selection topic
  doc/en/components/grids/_shared/cell-selection.md
Labels: status: do not merge, status: awaiting-test

#805 Grid conditional styling topic updates
  doc/en/components/grids/_shared/conditional-cell-styling.md
Labels: status: verified

#859 [JA] Latest changes - vnext
  doc/jp/components/charts/features/chart-axis-gridlines.md
  doc/jp/components/charts/features/chart-overlays.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/charts/types/line-chart.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/layouts/dock-manager.md
  docfx/jp/components/toc.json
Labels: status: localized

#855 Change file separator when verifying markdown to be OS agnostic. This…
  gulpfile.js
Labels: status: awaiting-test

#873 mdd-toolbar-updates
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  doc/en/components/menus/toolbar.md
Labels: status: in-review

#839 Ttonev/cell editing update
  doc/en/components/grids/_shared/cell-editing.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#875 mdd-angular-16-update
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#876 update toolbar doc
  doc/en/components/menus/toolbar.md
Labels: status: in-review

#878 [JA] Latest Help changes
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/menus/toolbar.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#841 Add live data topic with first sample.
  doc/en/components/grids/_shared/live-data.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#832 Update row selection topic - update wc and blazor snippets.
  doc/en/components/grids/_shared/row-selection.md
Labels: status: verified

#831 Fix Row pinning snippets
  doc/en/components/grids/_shared/row-pinning.md
Labels: status: verified

#845 Adding cascading combo topic.
  doc/en/components/grids/_shared/cascading-combos.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#824 Update Grid keyboard navigation topic.
  doc/en/components/grids/_shared/keyboard-navigation.md
Labels: status: verified

#822 Grid Summary - update snippets and add styling.
  doc/en/components/grids/_shared/summaries.md
Labels: status: verified

#811 add styling section for column resizing topic
  doc/en/components/grids/_shared/column-resizing.md
Labels: status: verified

#881 mdd-update
  doc/en/components/menus/toolbar.md
Labels: status: in-review

#884 Mdd update tags
  docfx/en/components/toc.json
Labels: status: in-review

#829 Add row drag snippets and missed sections.
  doc/en/components/grids/_shared/row-drag.md
Labels: status: verified

#886 mdd-update-toolbar
  doc/en/components/menus/toolbar.md
Labels: status: in-review

#892 mdd-update-versions-docsconfig
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  doc/en/components/menus/toolbar.md
  doc/jp/components/charts/features/chart-axis-types.md
  docConfig.json
Labels: status: in-review

#893 mdd-update-toolbar-landing-for-category
  doc/en/components/menus/toolbar.md
Labels: status: in-review

#894 Update general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-blazor.md
Labels: status: in-review

#897 [JP] Adding the latest content changes - up to 28 June.
  doc/jp/components/charts/features/chart-axis-types.md
  doc/jp/components/charts/features/chart-overlays.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/charts/types/sparkline-chart.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/cascading-combos.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/menus/toolbar.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#851 Remove razor language replacement
  src/ext/MarkdownTransformer.ts
Labels: status: awaiting-test

#890 refactor(combo): update the overview docs
  doc/en/components/inputs/combo/overview.md
Labels: status: verified, topic: combo

#904 Update chart-data-aggregations.md
  doc/en/components/charts/features/chart-data-aggregations.md
Labels: status: in-review

#905 added override for LOB API links in WC config
  doc/en/components/grids/_shared/row-selection.md
  docConfig.json
  package-lock.json
  yarn.lock
Labels: status: in-review
