Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-09, with the labels that each got.

#943 Add master-detail topic for React
  doc/en/components/grids/grid/master-detail.md
  docfx/en/components/toc.json
Labels: status: do not merge, status: verified

#949 Fix react keyword mappings
  docComponents.json
  docConfig.json
Labels: status: awaiting-test

#955 Add column resizing topic for React. Polish the topic for the other p…
  doc/en/components/grids/_shared/column-resizing.md
Labels: status: do not merge, status: verified

#954 Add React column moving topic
  doc/en/components/grids/_shared/column-moving.md
Labels: status: do not merge, status: verified

#966 Enable react paging topic
  doc/en/components/grids/_shared/paging.md
Labels: status: verified

#976 Enable row selection topic for React
  doc/en/components/grids/_shared/row-selection.md
Labels: status: verified

#957 Enable React conditional styling topic. Fix some snippets for other p…
  doc/en/components/grids/_shared/conditional-cell-styling.md
Labels: status: verified

#958 Enable display density react topic
  doc/en/components/grids/_shared/display-density.md
Labels: status: verified

#959 Enable editing topic for React
  doc/en/components/grids/_shared/editing.md
Labels: status: verified

#950 [JA] Latest doc changes
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/inputs/combo/single-selection.md
Labels: status: localized, status: verified

#960 Add column-pinning topic for React
  doc/en/components/grids/_shared/column-pinning.md
Labels: status: verified

#978 Enable react summaries topic
  doc/en/components/grids/_shared/summaries.md
Labels: status: verified

#965 Enable react grid overview topic
  doc/en/components/grids/data-grid.md
  doc/en/components/themes/overview.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#952 Add react cell selection topic
  doc/en/components/grids/_shared/cell-selection.md
Labels: status: verified

#951 Add filtering topic for React
  doc/en/components/grids/_shared/filtering.md
Labels: status: verified

#956 Enable column selection topic for React. Update the styling section
  doc/en/components/grids/_shared/column-selection.md
Labels: status: verified

#988 Add column types react topic
  doc/en/components/grids/_shared/column-types.md
Labels: status: verified

#987 Add column hiding topic for React
  doc/en/components/grids/_shared/column-hiding.md
Labels: status: verified

#990 Add row pinning topic for react
  doc/en/components/grids/_shared/row-pinning.md
Labels: status: verified

#932 Add Dock Manager customization topic
  doc/en/components/layouts/dock-manager-customization.md
  docfx/en/components/toc.json
Labels: status: verified, topic: dock-manager, status: awaiting-localization

#985 Add selection topic for React
  doc/en/components/grids/_shared/row-drag.md
  doc/en/components/grids/_shared/selection.md
Labels: status: verified

#947 Add excel style filtering topic for React
  doc/en/components/grids/_shared/excel-style-filtering.md
Labels: status: verified

#944 [React] Advanced Filtering Topic
  doc/en/components/grids/_shared/advanced-filtering.md
Labels: topic: grids, status: verified, platform: react, grids: filtering

#964 [React] Row Adding Topic
  doc/en/components/grids/_shared/row-adding.md
Labels: topic: grids, status: verified, platform: react, grids: row-adding

#994 [React] Grid Toolbar Topic
  doc/en/components/grids/_shared/toolbar.md
Labels: topic: grids, status: verified, platform: react, grids: toolbar

#989 [React] Exporting topic
  doc/en/components/grids/_shared/export-excel.md
Labels: topic: grids, status: verified, platform: react, grids: excel-export

#981 [React] Live-data Topic
  doc/en/components/grids/_shared/live-data.md
Labels: topic: grids, status: verified, status: awaiting-sample, platform: react

#974 docs(*): update docs with new sizing changes
  doc/en/components/grids/list.md
  doc/en/components/inputs/button.md
  doc/en/components/inputs/chip.md
  doc/en/components/inputs/icon-button.md
  doc/en/components/inputs/input.md
  doc/en/components/inputs/select.md
  doc/en/components/layouts/avatar.md
  doc/en/components/layouts/icon.md
  doc/en/components/scheduling/calendar.md
Labels: status: verified, status: awaiting-localization

#986 [React] Cell-editing Topic
  doc/en/components/grids/_shared/cell-editing.md
Labels: topic: grids, status: verified, platform: react, grids: cell-editing

#961 [React] Grid Group-by Topic
  doc/en/components/grids/grid/groupby.md
Labels: topic: grids, status: awaiting-test, status: in-review, platform: react, grids: group-by

#963 [React] Row Actions Topic
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/row-actions.md
Labels: status: in-development, topic: grids, platform: react, grids: row-actions

#993 React documentation
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/cell-editing.md
  doc/en/components/grids/_shared/cell-selection.md
  doc/en/components/grids/_shared/column-hiding.md
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/_shared/column-resizing.md
  doc/en/components/grids/_shared/column-selection.md
  doc/en/components/grids/_shared/column-types.md
  doc/en/components/grids/_shared/conditional-cell-styling.md
  doc/en/components/grids/_shared/display-density.md
  doc/en/components/grids/_shared/editing.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/export-excel.md
  doc/en/components/grids/_shared/filtering.md
  doc/en/components/grids/_shared/live-data.md
  doc/en/components/grids/_shared/paging.md
  doc/en/components/grids/_shared/remote-data-operations.md
  doc/en/components/grids/_shared/row-actions.md
  doc/en/components/grids/_shared/row-adding.md
  doc/en/components/grids/_shared/row-drag.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/_shared/row-pinning.md
  doc/en/components/grids/_shared/row-selection.md
  doc/en/components/grids/_shared/search.md
  doc/en/components/grids/_shared/selection.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/_shared/toolbar.md
  doc/en/components/grids/data-grid.md
  doc/en/components/grids/grid/groupby.md
  doc/en/components/grids/grid/master-detail.md
  doc/en/components/themes/overview.md
  docComponents.json
  docConfig.json
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  package-lock.json
  package.json
  src/ext/MarkdownTransformer.ts
  stats/docStats-React.json
  yarn.lock
Labels: status: awaiting-localization, platform: react
