Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-04, with the labels that each got.

#733 Update combo docs to include Blazor
  doc/en/components/inputs/combo/features.md
  doc/en/components/inputs/combo/overview.md
  doc/en/components/inputs/combo/single-selection.md
  doc/en/components/inputs/combo/templates.md
  doc/jp/components/inputs/combo/features.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/inputs/combo/single-selection.md
  doc/jp/components/inputs/combo/templates.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: area: enhancement, status: verified

#750 Mdd changelog
  doc/en/components/excel-library.md
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#761 [JA] Localization changes
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/types/donut-chart.md
  doc/jp/components/charts/types/polar-chart.md
  doc/jp/components/excel-library-working-with-grids.md
  doc/jp/components/excel-library.md
  doc/jp/components/excel-utility.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started-blazor-client.md
  doc/jp/components/general-getting-started-blazor-maui.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/general-nuget-feed.md
  doc/jp/components/geo-map-binding-data-csv.md
  doc/jp/components/geo-map-binding-data-model.md
  doc/jp/components/geo-map-binding-multiple-sources.md
  doc/jp/components/geo-map-display-heat-imagery.md
  doc/jp/components/geo-map-resources-esri.md
  doc/jp/components/geo-map-type-scatter-bubble-series.md
  doc/jp/components/geo-map-type-scatter-contour-series.md
  doc/jp/components/geo-map-type-shape-polyline-series.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/data-grid/column-chooser.md
  doc/jp/components/grids/data-grid/column-pinning.md
  doc/jp/components/grids/data-grid/column-summaries.md
  doc/jp/components/grids/data-grid/column-types.md
  doc/jp/components/grids/data-grid/remote-data.md
  doc/jp/components/grids/data-grid/type-sparkline-table.md
  doc/jp/components/grids/grid/paste-excel.md
  doc/jp/components/grids/pivot-grid/features.md
  doc/jp/components/grids/pivot-grid/overview.md
  doc/jp/components/inputs/select.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/layouts/tabs.md
  doc/jp/components/maps/map-api.md
  doc/jp/components/radial-gauge.md
  doc/jp/components/spreadsheet-overview.md
  doc/jp/components/zoomslider-overview.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#765 Mdd update changelog wc
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-wc.md
Labels: status: in-review

#766 mdd-update-formatting-changelog
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-wc.md
Labels: status: in-review

#767 Update docConfig.json
  docConfig.json
Labels: status: in-review

#771 mdd-capialize-properties-blazor
  doc/en/components/general-changelog-dv-blazor.md
Labels: status: in-review

#769 [JA] Adding localization changes
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/advanced-filtering.md
Labels: status: localized

#778 mdd-update
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-wc.md
Labels: status: in-review

#781 [JA] Latest topic changes
  doc/jp/components/blazor-excel-library-temporarily-stop-automatic-calculation-of-formulas-to-speed-up-processing.md
  doc/jp/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md
  doc/jp/components/customize-marker-display-in-blazor-charts.md
  doc/jp/components/excel-library.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/_shared/virtualization.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/data-grid/column-pinning.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/inputs/combo/overview.md
  docfx/jp/components/toc.json
Labels: status: localized

#775 fix(dialog): fix Blazor related content
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/notifications/dialog.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#790 [JP] Adding the latest content changes - 18 Apr 23
  doc/jp/components/blazor-excel-library-temporarily-stop-automatic-calculation-of-formulas-to-speed-up-processing.md
  doc/jp/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md
  doc/jp/components/bullet-graph.md
  doc/jp/components/customize-marker-display-in-blazor-charts.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/notifications/dialog.md
Labels: status: localized

#789 ci(gh-actions): build should fail for broken links
  docfx/en/global.json
  docfx/jp/global.json
  docfx/kr/global.json
Labels: status: verified

#741 Update stepper topic for Blazor
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/layouts/stepper.md
  docfx/en/components/toc.json
Labels: status: verified, topic: stepper

#799 mdd-update-row-dragging-topic
  doc/en/components/grids/_shared/row-drag.md
Labels: status: verified

#801 Warnings are not Errors
  docfx/en/global.json
Labels: status: in-review

#806 fix typos and links
  doc/en/components/charts/features/chart-axis-types.md
  doc/en/components/layouts/accordion.md
  doc/en/components/layouts/expansion-panel.md
  doc/jp/components/charts/features/chart-axis-types.md
  doc/jp/components/layouts/accordion.md
  doc/jp/components/layouts/expansion-panel.md
Labels: status: verified
