Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-11, with the labels that each got.

#1014 Add button group topic
  doc/en/components/inputs/button-group.md
  docfx/en/components/toc.json
Labels: status: verified, status: awaiting-localization

#856 Add Load on Demand topic for WebComponents.
  doc/en/components/grids/tree-grid/load-on-demand.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#1069 [Localization] Updating JP for #1029
  doc/jp/components/grids/_shared/multi-column-headers.md
Labels: status: localized, status: verified

#1071 [Localization] Adding Button Group
  doc/jp/components/inputs/button-group.md
Labels: status: localized

#1077 [JA] Tree Grid Load on Demand
  doc/en/components/grids/tree-grid/load-on-demand.md
  doc/jp/components/grids/tree-grid/load-on-demand.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#1048 [React] Add advanced-filtering topic
  doc/en/components/grids/_shared/advanced-filtering.md
Labels: topic: grids, status: awaiting-test, platform: react, grids: filtering

#1073 [React] Update general-cli-overview.md topic
  doc/en/components/general-cli-overview.md
Labels: status: verified, platform: react

#1081 [JA] Latest changes - vnext
  doc/jp/components/general-cli-overview.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/export-excel.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#1075 [WC] Add missing snippet for cell-editing.md
  doc/en/components/grids/_shared/cell-editing.md
Labels: status: awaiting-test, grids: cell-editing, platform: wc

#1087 mdd-added vertical orientation
  doc/en/components/menus/toolbar.md
Labels: status: in-review
