Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-12, with the labels that each got.

#1089 [JA] Latest localization changes and fixes
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/inputs/button.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/menus/toolbar.md
Labels: status: localized

#1088 Mdd bug fixes 23.2
  doc/en/components/charts/types/column-chart.md
  doc/en/components/general-getting-started-blazor-client.md
  doc/en/components/general-getting-started.md
  doc/en/components/inputs/dropdown.md
Labels: status: in-review

#1091 Update cell-editing.md
  doc/en/components/grids/_shared/cell-editing.md
Labels: status: in-review

#1097 docs(*): add reference to getting started topic
  doc/en/components/general-getting-started.md
  doc/en/components/grids/list.md
  doc/en/components/grids/tree.md
  doc/en/components/inputs/badge.md
  doc/en/components/inputs/button-group.md
  doc/en/components/inputs/button.md
  doc/en/components/inputs/checkbox.md
  doc/en/components/inputs/chip.md
  doc/en/components/inputs/circular-progress.md
  doc/en/components/inputs/combo/overview.md
  doc/en/components/inputs/date-time-input.md
  doc/en/components/inputs/dropdown.md
  doc/en/components/inputs/form.md
  doc/en/components/inputs/icon-button.md
  doc/en/components/inputs/input.md
  doc/en/components/inputs/linear-progress.md
  doc/en/components/inputs/mask-input.md
  doc/en/components/inputs/radio.md
  doc/en/components/inputs/rating.md
  doc/en/components/inputs/ripple.md
  doc/en/components/inputs/select.md
  doc/en/components/inputs/slider.md
  doc/en/components/inputs/switch.md
  doc/en/components/layouts/accordion.md
  doc/en/components/layouts/avatar.md
  doc/en/components/layouts/card.md
  doc/en/components/layouts/expansion-panel.md
  doc/en/components/layouts/icon.md
  doc/en/components/layouts/stepper.md
  doc/en/components/layouts/tabs.md
  doc/en/components/menus/navbar.md
  doc/en/components/menus/navigation-drawer.md
  doc/en/components/notifications/dialog.md
  doc/en/components/notifications/snackbar.md
  doc/en/components/notifications/toast.md
  doc/en/components/scheduling/calendar.md
Labels: status: verified

#1098 Fix inconsistency between topic and sample in Pivot Grid overview.md
  doc/en/components/grids/pivot-grid/overview.md
Labels: bug: in-docs, status: awaiting-test, bug: in-snippets, platform: blazor, platform: wc

#1074 update getting started
  doc/en/components/general-getting-started.md
  doc/en/images/general/grid-geo-map.png
  docConfig.json
Labels: status: awaiting-test

#1101 Updating State Persistence topic - JA, other fixes.
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/state-persistence.md
  docfx/jp/components/toc.json
Labels: status: localized

#915 Enable kb nav treegrid topic and fix snippets.
  doc/en/components/grids/_shared/keyboard-navigation.md
  docfx/en/components/toc.json
Labels: status: verified

#914 Update tree grid snippets for editing topic.
  doc/en/components/grids/_shared/editing.md
  docfx/en/components/toc.json
Labels: status: verified

#879 Update column types topic for tree grid
  doc/en/components/grids/_shared/column-types.md
  docfx/en/components/toc.json
Labels: status: verified

#1105 mdd-new-toolbar-updates
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  doc/en/components/menus/toolbar.md
  docConfig.json
Labels: status: in-review

#1106 Updating JA with the latest topic changes and fixes.
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/menus/toolbar.md
  docfx/jp/components/toc.json
Labels: status: localized

#862 Update TreeGrid Advanced Filtering snippets and show in TOC.
  doc/en/components/grids/_shared/advanced-filtering.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: in-review
