Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-03, with the labels that each got.

#698 [JA] Adding changes up to 1st March
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/row-pinning.md
  docfx/jp/components/toc.json
Labels: area: localization

#706 Remove navbar components button
  docfx/en/toc.yml
  docfx/jp/toc.yml
  docfx/kr/toc.yml
  package-lock.json
  package.json
  yarn.lock
Labels: status: verified

#708 [JA] Updating licensing topic
  doc/jp/components/general-licensing.md
Labels: area: localization, status: localized, status: verified

#681 Adding Angular build and PR automation
  azure-pipelines/build-pipeline-jp+kr.yml
  azure-pipelines/build-pipeline.yml
  azure-pipelines/templates/build-steps-make-pr.yml
  azure-pipelines/templates/build-steps-template.yml
Labels: status: in-development, squash-merge

#716 Update README.md
  README.md
Labels: status: in-review

#711 [JA] Localization updates
  doc/jp/components/charts/features/chart-axis-types.md
  doc/jp/components/grids/combo/overview.md
  doc/jp/components/grids/combo/single-selection.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#719 Update toc.json
  docfx/en/components/toc.json
Labels: status: in-review

#727 chore(*): marketing-update-tree-23-mar-23
  doc/en/components/grids/tree.md
Labels: topic: tree

#735 [JA] Latest localization updates
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/tree.md
  doc/jp/components/notifications/dialog.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#740 mdd-update-tree-nav
  docfx/en/components/toc.json
Labels: status: in-review

#743 [JA] Localization updates
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/inputs/radio.md
  docfx/jp/components/toc.json
Labels: status: localized

#739 refactor(select): add razor snippets
  doc/en/components/inputs/select.md
  docfx/en/components/toc.json
Labels: area: enhancement, status: verified
