Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-01, with the labels that each got.

#635 [JA] Latest updates
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/grid/overview.md
  docfx/jp/components/toc.json
Labels: area: localization, status: localized, status: verified

#637 Grid Overview topic edits
  doc/en/components/grids/grid/overview.md
Labels: area: docs, status: awaiting-test

#628 Update template version
  package.json
  yarn.lock
Labels: status: do not merge, status: awaiting-test

#617 docs(pivot): port topic about remote operations in pivot WC only
  doc/en/components/grids/_shared/state-persistence.md
  doc/en/components/grids/grids-header.md
  doc/en/components/grids/pivot-grid/features.md
  doc/en/components/grids/pivot-grid/overview.md
  doc/en/components/grids/pivot-grid/remote-operations.md
  doc/en/components/zoomslider-overview.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/pivot-grid/overview.md
  doc/jp/components/zoomslider-overview.md
  doc/kr/components/zoomslider-overview.md
  docfx/en/components/toc.json
Labels: status: do not merge

#644 Mdd maui released
  doc/en/components/general-getting-started-blazor-maui.md
  doc/en/images/general/new-blazor-project-configure-maui.jpg
  doc/en/images/general/new-blazor-project-maui.jpg
Labels: status: in-review

#647 [JA] Adding changes up to 12 Jan 23
  doc/jp/components/bullet-graph.md
  doc/jp/components/charts/chart-features.md
  doc/jp/components/charts/chart-overview.md
  doc/jp/components/charts/features/chart-tooltips.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/excel-library.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started-blazor-maui.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/list.md
  doc/jp/components/grids/pivot-grid/overview.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/circular-progress.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/inputs/slider.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/linear-gauge.md
  doc/jp/components/notifications/dialog.md
  doc/jp/components/radial-gauge.md
  doc/jp/components/scheduling/calendar.md
  doc/jp/images/general/new-blazor-project-configure-maui.jpg
  doc/jp/images/general/new-blazor-project-maui.jpg
Labels: area: localization, status: localized, status: verified

#646 docs(dock-manager): describe CSS variables
  doc/en/components/layouts/dock-manager.md
Labels: area: docs, status: awaiting-test, dock-manager

#653 mdd-update-data-grid
  doc/en/components/grids/data-grid-accessibility.md
  doc/en/components/grids/data-grid-cell-activation.md
  doc/en/components/grids/data-grid-cell-editing.md
  doc/en/components/grids/data-grid-cell-merging.md
  doc/en/components/grids/data-grid-cell-selection.md
  doc/en/components/grids/data-grid-column-animation.md
  doc/en/components/grids/data-grid-column-chooser.md
  doc/en/components/grids/data-grid-column-filtering.md
  doc/en/components/grids/data-grid-column-moving.md
  doc/en/components/grids/data-grid-column-options.md
  doc/en/components/grids/data-grid-column-pinning.md
  doc/en/components/grids/data-grid-column-resizing.md
  doc/en/components/grids/data-grid-column-sorting.md
  doc/en/components/grids/data-grid-column-summaries.md
  doc/en/components/grids/data-grid-column-types.md
  doc/en/components/grids/data-grid-horizontal-scrolling.md
  doc/en/components/grids/data-grid-live-data.md
  doc/en/components/grids/data-grid-load-save-layout.md
  doc/en/components/grids/data-grid-local-data.md
  doc/en/components/grids/data-grid-localization.md
  doc/en/components/grids/data-grid-performance.md
  doc/en/components/grids/data-grid-remote-data.md
  doc/en/components/grids/data-grid-row-grouping.md
  doc/en/components/grids/data-grid-row-highlighting.md
  doc/en/components/grids/data-grid-row-paging.md
  doc/en/components/grids/data-grid-row-pinning.md
  doc/en/components/grids/data-grid-type-comparison-table.md
  doc/en/components/grids/data-grid-type-heatmap-table.md
  doc/en/components/grids/data-grid-type-matrix-table.md
  doc/en/components/grids/data-grid-type-periodic-table.md
  doc/en/components/grids/data-grid-type-sparkline-table.md
  doc/en/components/grids/data-grid.md
Labels: status: in-review

#651 [JA] Updating dock-manager topics
  doc/jp/components/layouts/dock-manager-electron.md
  doc/jp/components/layouts/dock-manager.md
Labels: area: localization, status: localized, status: verified

#657 mdd - seo toast updates
  doc/en/components/notifications/toast.md
Labels: status: in-review

#656 mdd - update dropdown for seo
  doc/en/components/inputs/dropdown.md
Labels: status: in-review

#655 mdd - seo tabs update
  doc/en/components/layouts/tabs.md
Labels: status: in-review

#654 mdd - update calendar seo
  doc/en/components/scheduling/calendar.md
Labels: status: in-review

#658 [JA] Updating with latest localized content
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/data-grid-accessibility.md
  doc/jp/components/grids/data-grid-cell-activation.md
  doc/jp/components/grids/data-grid-cell-merging.md
  doc/jp/components/grids/data-grid-column-animation.md
  doc/jp/components/grids/data-grid-column-chooser.md
  doc/jp/components/grids/data-grid-column-filtering.md
  doc/jp/components/grids/data-grid-column-options.md
  doc/jp/components/grids/data-grid-column-pinning.md
  doc/jp/components/grids/data-grid-column-resizing.md
  doc/jp/components/grids/data-grid-column-sorting.md
  doc/jp/components/grids/data-grid-column-summaries.md
  doc/jp/components/grids/data-grid-column-types.md
  doc/jp/components/grids/data-grid-horizontal-scrolling.md
  doc/jp/components/grids/data-grid-live-data.md
  doc/jp/components/grids/data-grid-load-save-layout.md
  doc/jp/components/grids/data-grid-local-data.md
  doc/jp/components/grids/data-grid-localization.md
  doc/jp/components/grids/data-grid-performance.md
  doc/jp/components/grids/data-grid-remote-data.md
  doc/jp/components/grids/data-grid-row-grouping.md
  doc/jp/components/grids/data-grid-row-highlighting.md
  doc/jp/components/grids/data-grid-row-paging.md
  doc/jp/components/grids/data-grid-type-comparison-table.md
  doc/jp/components/grids/data-grid-type-heatmap-table.md
  doc/jp/components/grids/data-grid-type-matrix-table.md
  doc/jp/components/grids/data-grid-type-periodic-table.md
  doc/jp/components/grids/data-grid-type-sparkline-table.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/layouts/tabs.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/scheduling/calendar.md
Labels: area: localization, status: localized, status: verified
