Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-10, with the labels that each got.

#953 docs(stepper): add animations section
  doc/en/components/inputs/radio.md
  doc/en/components/layouts/stepper.md
Labels: status: verified, topic: stepper, status: awaiting-localization

#1000 [JA] Latest changes
  doc/jp/components/charts/types/area-chart.md
  doc/jp/components/charts/types/bubble-chart.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/data-grid/accessibility.md
  doc/jp/components/grids/data-grid/cell-activation.md
  doc/jp/components/grids/list.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/select.md
  doc/jp/components/layouts/accordion.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/dock-manager-customization.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/scheduling/calendar.md
  docfx/jp/components/toc.json
Labels: status: localized, status: in-test

#992 mdd-update
  doc/en/components/general-getting-started-blazor-client.md
  doc/en/components/general-getting-started.md
Labels: status: in-review

#1013 [JP] Adding the latest content changes - 6 Oct 2023
  doc/jp/components/general-getting-started-blazor-client.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/select.md
  doc/jp/components/layouts/dock-manager-customization.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/themes/overview.md
  docfx/jp/components/toc.json
Labels: status: localized

#1023 chore(*): grid-features-description-updates
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/batch-editing.md
  doc/en/components/grids/_shared/cascading-combos.md
  doc/en/components/grids/_shared/cell-editing.md
  doc/en/components/grids/_shared/cell-selection.md
  doc/en/components/grids/_shared/clipboard-interactions.md
  doc/en/components/grids/_shared/collapsible-column-groups.md
  doc/en/components/grids/_shared/column-hiding.md
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/_shared/column-resizing.md
  doc/en/components/grids/_shared/column-selection.md
  doc/en/components/grids/_shared/column-types.md
  doc/en/components/grids/_shared/conditional-cell-styling.md
  doc/en/components/grids/_shared/display-density.md
  doc/en/components/grids/_shared/editing.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/export-excel.md
  doc/en/components/grids/_shared/filtering.md
  doc/en/components/grids/_shared/keyboard-navigation.md
  doc/en/components/grids/_shared/live-data.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/multi-row-layout.md
  doc/en/components/grids/_shared/paging.md
  doc/en/components/grids/_shared/remote-data-operations.md
  doc/en/components/grids/_shared/row-actions.md
  doc/en/components/grids/_shared/row-adding.md
  doc/en/components/grids/_shared/row-drag.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/_shared/row-pinning.md
  doc/en/components/grids/_shared/row-selection.md
  doc/en/components/grids/_shared/search.md
  doc/en/components/grids/_shared/selection.md
  doc/en/components/grids/_shared/sizing.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/state-persistence.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/_shared/toolbar.md
  doc/en/components/grids/_shared/validation.md
Labels: topic: grids, status: awaiting-localization

#1031 chore(*): grid-features-description-updates
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/cascading-combos.md
  doc/en/components/grids/_shared/cell-editing.md
  doc/en/components/grids/_shared/cell-selection.md
  doc/en/components/grids/_shared/collapsible-column-groups.md
  doc/en/components/grids/_shared/column-resizing.md
  doc/en/components/grids/_shared/conditional-cell-styling.md
  doc/en/components/grids/_shared/display-density.md
  doc/en/components/grids/_shared/editing.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/export-excel.md
  doc/en/components/grids/_shared/filtering.md
  doc/en/components/grids/_shared/keyboard-navigation.md
  doc/en/components/grids/_shared/live-data.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/paging.md
  doc/en/components/grids/_shared/remote-data-operations.md
  doc/en/components/grids/_shared/row-actions.md
  doc/en/components/grids/_shared/row-adding.md
  doc/en/components/grids/_shared/row-drag.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/_shared/row-pinning.md
  doc/en/components/grids/_shared/row-selection.md
  doc/en/components/grids/_shared/search.md
  doc/en/components/grids/_shared/selection.md
  doc/en/components/grids/_shared/sizing.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/state-persistence.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/_shared/toolbar.md
  doc/en/components/grids/_shared/validation.md
  doc/en/components/grids/grid/groupby.md
Labels: topic: grids, status: awaiting-localization

#1021 Add cascading combo - react snippets.
  doc/en/components/grids/_shared/cascading-combos.md
Labels: status: verified

#1019 Add snippets and correct sample for collapsible col groups.
  doc/en/components/grids/_shared/collapsible-column-groups.md
Labels: status: verified

#1032 [JA] Latest changes
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/batch-editing.md
  doc/jp/components/grids/_shared/cascading-combos.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/clipboard-interactions.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sizing.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/menus/toolbar.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#1001 Enable clipboard interactions topic for all platforms
  docfx/en/components/toc.json
Labels: status: verified

#867 Enable treegrid collapsible column groups topic with minor fixes.
  doc/en/components/grids/_shared/collapsible-column-groups.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#864 Enable tree grid clipboard interaction in TOC.
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: verified

#1017 fix(docs): removed mentions of browser in electron
  doc/en/components/layouts/dock-manager-electron.md
Labels: status: in-review, status: awaiting-localization

#1045 [JA] Updating topics with the latest changes - 20 Oct - vnext
  doc/jp/components/general-licensing.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cascading-combos.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sizing.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/grids/grid/selection-based-aggregates.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#1064 Update chart-overview.md
  doc/en/components/charts/chart-overview.md
Labels: status: in-review
