Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2023-07, with the labels that each got.

#810 Update column hiding topic to use component selector for samples when applicable.
  doc/en/components/grids/_shared/column-hiding.md
Labels: status: awaiting-test

#909 [JA] Latest doc changes
  doc/jp/components/charts/features/chart-data-aggregations.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/menus/toolbar.md
Labels: status: localized, status: verified

#858 Update event handlings in code snippets to work.
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/_shared/export-excel.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/row-actions.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/data-grid.md
Labels: status: in-development

#809 Grid Filtering - Fix WC/Blazor grid snippets and sections. Add styling.
  doc/en/components/grids/_shared/filtering.md
Labels: status: in-review

#916 [JA] Latest doc changes
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/data-grid.md
  docfx/jp/components/toc.json
Labels: status: localized, status: verified

#925 merge vnext latest fixes
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/cell-editing.md
  doc/en/components/grids/_shared/cell-selection.md
  doc/en/components/grids/_shared/column-hiding.md
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/_shared/column-resizing.md
  doc/en/components/grids/_shared/column-selection.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/export-excel.md
  doc/en/components/grids/_shared/filtering.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/multi-row-layout.md
  doc/en/components/grids/_shared/row-actions.md
  doc/en/components/grids/_shared/row-adding.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/_shared/row-pinning.md
  doc/en/components/grids/_shared/row-selection.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/_shared/toolbar.md
  doc/en/components/grids/_shared/validation.md
  doc/en/components/grids/data-grid.md
  doc/en/components/grids/grid/groupby.md
  doc/en/components/grids/grid/master-detail.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/data-grid.md
  docfx/jp/components/toc.json
  gulpfile.js
  src/ext/MarkdownTransformer.ts
Labels: status: in-review

#928 [JA] Updating css vars as per EN
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/validation.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/grid/master-detail.md
Labels: status: localized, status: verified

#927 fixed API and added buildSatats script
  TESTING.md
  doc/en/components/geo-map-binding-data-csv.md
  docStats-Angular.json
  docStats-Blazor.json
  docStats-React.json
  docStats-WC.json
  gulpfile.js
  src/ext/MappingLoader.ts
  src/ext/MarkdownTransformer.ts
Labels: status: in-review

#934 mdd-change-to-template-sample
  doc/en/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
Labels: status: in-review

#935 refactor(rating): add blazor-related docs
  doc/en/components/inputs/rating.md
  docfx/en/components/toc.json
Labels: status: verified, topic: rating
