Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-09, with the labels that each got.

#1355 Update JA with the latest changes - Proportional Category Angle Axis, Changelogs
  doc/jp/components/charts/features/chart-axis-types.md
  doc/jp/components/charts/features/chart-data-selection.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/size.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grids-header.md
  doc/jp/components/grids/pivot-grid/features.md
  doc/jp/components/grids/pivot-grid/overview.md
  doc/jp/components/interactivity/accessibility-compliance.md
  doc/jp/images/general/greenCheck.png
  doc/jp/images/general/redX.png
  docfx/jp/components/toc.json
Labels: status: localized

#1361 Fix React and Blazor Date Picker missing sections
  doc/en/components/scheduling/date-picker.md
Labels: status: awaiting-test :x:

#1365 [JA] Date Picker updates, XDate Picker, Icon topic, other
  doc/jp/components/charts/types/data-pie-chart.md
  doc/jp/components/editors/date-picker.md
  doc/jp/components/editors/xdate-picker.md
  doc/jp/components/grids/_shared/size.md
  doc/jp/components/grids/grid/icons.md
  doc/jp/components/grids/hierarchical-grid/overview.md
  doc/jp/components/inputs/slider.md
  doc/jp/components/scheduling/date-picker.md
  docfx/jp/components/toc.json
Labels: status: localized

#1364 Remove Form topic and all related links.
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/inputs/form.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/kr/components/general-changelog-dv.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: verified :white_check_mark:

#1363 Fix snippets for hgrid editing feature integration
  doc/en/components/grids/_shared/editing.md
Labels: status: verified :white_check_mark:

#1359 mdd-AUG-18.1.0-angular update
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review :eyes:

#1306 mdd-highlight-label
  doc/en/components/radial-gauge.md
Labels: status: in-review :eyes:

#1366 Updating JA with the latest changes - Changelog, Editing, Radial Gauge
  doc/jp/components/charts/features/chart-data-selection.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/inputs/form.md
  doc/jp/components/radial-gauge.md
Labels: status: localized

#1358 Add Banner topic for React/Blazor
  apiMap/Blazor/webInputs.JS.blazor.apiMap.json
  apiMap/React/webInputs.JS.r.apiMap.json
  doc/en/components/notifications/banner.md
  docConfig.json
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:, platform: react, platform: blazor, topic: banner, status: pending-localization :symbols:

#1368 docs(button-group): enable selection sample for React
  doc/en/components/inputs/button-group.md
Labels: status: verified :white_check_mark:, platform: react, button-group

#1378 dv sept to changelog
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review :eyes:

#1382 update changelog
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review :eyes:

#1381 Updating JA Changelogs - September release
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/inputs/button-group.md
Labels: status: localized

#1379 Update api maps for DatePicker for React and Blazor
  apiMap/Blazor/webInputs.JS.blazor.apiMap.json
  apiMap/React/webInputs.JS.r.apiMap.json
Labels: platform: react, platform: blazor

#1386 Update JP changelogs with the latest changes, other fixes to match EN
  doc/jp/components/charts/chart-api.md
  doc/jp/components/charts/types/data-pie-chart.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/hierarchical-grid/overview.md
Labels: status: localized

#1211 mdd-update-toc
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/cell-editing.md
  doc/en/components/grids/_shared/cell-selection.md
  doc/en/components/grids/_shared/column-hiding.md
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/_shared/column-resizing.md
  doc/en/components/grids/_shared/column-selection.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/filtering.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/multi-row-layout.md
  doc/en/components/grids/_shared/row-editing.md
  doc/en/components/grids/_shared/row-pinning.md
  doc/en/components/grids/_shared/sorting.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/_shared/toolbar.md
  doc/en/components/grids/_shared/virtualization.md
  doc/en/components/grids/data-grid.md
  doc/en/components/grids/grid/groupby.md
  doc/en/components/grids/hierarchical-grid/overview.md
  doc/en/components/grids/theming-grid.md
  doc/en/components/grids/tree-grid/overview.md
  doc/jp/components/grids/_shared/virtualization.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
Labels: status: in-review :eyes:

#1390 Updating JA with the latest changes - theming, API
  doc/jp/components/charts/chart-api.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-selection.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/grids/hierarchical-grid/overview.md
  doc/jp/components/grids/theming-grid.md
  doc/jp/components/grids/tree-grid/overview.md
  doc/jp/components/layouts/divider.md
  docfx/jp/components/toc.json
Labels: status: localized
