Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-03, with the labels that each got.

#1179 mdd-data-legend-tooltip-grouping
  doc/en/components/charts/features/chart-data-legend.md
  doc/en/components/charts/features/chart-data-tooltip.md
  doc/en/components/charts/features/chart-highlight-filter.md
Labels: status: in-review

#1178 Fix Grid Mater-Detail topic title
  doc/en/components/grids/grid/master-detail.md
Labels: topic: grids, status: awaiting-test

#1187 Mdd rg optical scaling
  doc/en/components/radial-gauge.md
  docfx/en/components/toc.json
  docfx/kr/components/toc.json
Labels: status: in-review

#1155 [React] Stepper topic
  doc/en/components/layouts/stepper.md
  doc/en/images/stepper/stepper-contentTop.png
  docfx/en/components/toc.json
Labels: squash-merge, topic: stepper, platform: react

#1186 [JA] Hierarchical Grid topic updates, Data Legend, Tooltip Grouping
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-highlight-filter.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/grids/hierarchical-grid/overview.md
  doc/jp/components/grids/tree-grid/overview.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/radial-gauge.md
  doc/jp/images/stepper/stepper-contentTop.png
  doc/jp/images/unfold_less_icon_screenshot.jpg
  docfx/jp/components/toc.json
Labels: status: localized

#1177 [JA] Updating Dialog topic - React
  doc/jp/components/notifications/dialog.md
Labels: status: localized, topic: dialog

#1216 Stepper: enable animation section in react
  doc/en/components/layouts/stepper.md
Labels: status: in-review

#1217 mdd-increase-iframe
  doc/en/components/radial-gauge.md
  doc/jp/components/radial-gauge.md
Labels: status: in-review

#1218 Enable Animation section in React - JA
  doc/jp/components/layouts/stepper.md
Labels: status: localized

#1222 mdd-misc-fixes-3/27
  doc/en/components/charts/features/chart-highlighting.md
  doc/en/components/inputs/combo/single-selection.md
  doc/kr/components/charts/features/chart-highlighting.md
Labels: status: in-review

#1229 mdd-remove-grouping
  doc/en/components/charts/features/chart-data-legend.md
  doc/en/components/charts/features/chart-data-tooltip.md
  doc/en/components/charts/features/chart-highlight-filter.md
Labels: status: in-review

#1231 mdd-remove-extra-char
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
Labels: status: in-review

#1226 Updating JA for #1222 - Chart Highlighting.
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-highlight-filter.md
  doc/jp/components/charts/features/chart-highlighting.md
Labels: status: localized

#1233 mdd-update-angular
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#1234 Updating JA changelogs for 23.2 March release
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/radial-gauge.md
Labels: status: localized
