Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-04, with the labels that each got.

#1238 Update general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
Labels: status: in-review

#1239 Updating JA changelogs
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/tree.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/stepper.md
Labels: status: localized

#1224 Add hGrid load on demand topic
  doc/en/components/grids/hierarchical-grid/load-on-demand.md
  doc/en/images/hgrid-database.jpg
  docfx/en/components/toc.json
Labels: status: verified

#1209 Add hgrid selection topic
  doc/en/components/grids/_shared/selection.md
  docfx/en/components/toc.json
Labels: status: verified

#1210 Add hgrid row editing topic
  doc/en/components/grids/_shared/row-editing.md
  docfx/en/components/toc.json
Labels: status: verified

#1196 Add hgrid export excel topic
  doc/en/components/grids/_shared/export-excel.md
  docfx/en/components/toc.json
Labels: status: verified

#1197 Add hgrid multi column headers topic
  doc/en/components/grids/_shared/multi-column-headers.md
  docfx/en/components/toc.json
Labels: status: verified

#1200 Add hgrid sorting topic
  doc/en/components/grids/_shared/sorting.md
  docfx/en/components/toc.json
Labels: status: verified

#1203 Add hgrid row actions topic
  doc/en/components/grids/_shared/row-actions.md
  docfx/en/components/toc.json
Labels: status: verified

#1204 Add column moving topic
  doc/en/components/grids/_shared/column-moving.md
  docfx/en/components/toc.json
Labels: status: verified

#1206 Add hgrid sizing topic
  docfx/en/components/toc.json
Labels: status: verified

#1185 docs(hGrid): add column resizing topic
  doc/en/components/grids/_shared/column-resizing.md
  docfx/en/components/toc.json
Labels: status: do not merge

#1181 Add column types topic for the Hierarchical grid
  doc/en/components/grids/_shared/column-types.md
  docfx/en/components/toc.json
Labels: status: do not merge, status: verified

#1195 Add hgrid hiding topic
  doc/en/components/grids/_shared/column-hiding.md
  docfx/en/components/toc.json
Labels: status: verified

#1246 Updating JA hgrid topics to match the latest changes.
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/hierarchical-grid/load-on-demand.md
  doc/jp/images/hgrid-database.jpg
  docfx/jp/components/toc.json
Labels: status: localized

#1219 Add hGrid virtualization topic
  docfx/en/components/toc.json
Labels: status: verified

#1227 Add hgrid summary topic
  doc/en/components/grids/_shared/summaries.md
  docfx/en/components/toc.json
Labels: status: verified

#1212 Add hgrid editing topic
  doc/en/components/grids/_shared/editing.md
Labels: status: verified

#1199 Add hgrid cell selection topic
  doc/en/components/grids/_shared/cell-selection.md
  docfx/en/components/toc.json
Labels: status: verified

#1188 Add HierarchicalGrid column selection topic
  docfx/en/components/toc.json
Labels: status: verified

#1184 Add Hierarchical Grid Cell Editing topic
  doc/en/components/grids/_shared/cell-editing.md
  docfx/en/components/toc.json
Labels: squash-merge

#1223 Add hgrid row-drag topic
  doc/en/components/grids/_shared/row-drag.md
  docfx/en/components/toc.json
Labels: status: verified

#1213 Add hGrid toolbar topic
  doc/en/components/grids/_shared/toolbar.md
  docfx/en/components/toc.json
Labels: status: verified

#1242 mdd-191
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-development, status: in-review

#1201 Add hgrid row-adding topic and update toc
  doc/en/components/grids/_shared/row-adding.md
  docfx/en/components/toc.json
Labels: status: verified

#1183 Add hgrid display density topic
  doc/en/components/grids/_shared/display-density.md
  docfx/en/components/toc.json
Labels: status: verified

#1189 Add conditional styling topic for hgrid
  doc/en/components/grids/_shared/conditional-cell-styling.md
  docfx/en/components/toc.json
Labels: status: verified, squash-merge

#1180 Add Hierarchical Grid Collapsible Column Groups topic
  doc/en/components/grids/_shared/collapsible-column-groups.md
  docfx/en/components/toc.json
Labels: status: verified, squash-merge

#1171 Allowed filtering topics for HGrid
  doc/en/components/grids/_shared/advanced-filtering.md
  doc/en/components/grids/_shared/excel-style-filtering.md
  doc/en/components/grids/_shared/filtering.md
  docfx/en/components/toc.json
Labels: status: verified, topic: hierarchical-grid

#1261 Update hGrid LOD topic
  doc/en/components/grids/hierarchical-grid/load-on-demand.md
  doc/en/components/grids/hierarchical-grid/overview.md
Labels: status: verified, platform: react, platform: blazor, platform: wc, topic: hierarchical-grid

#1267 mdd-update-xplat-blazor-23.2.204
  docConfig.json
Labels: status: in-review

#1264 [JA] Updating changelogs, shared topics.
  doc/jp/components/charts/types/pie-chart.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/hierarchical-grid/load-on-demand.md
  doc/jp/components/grids/hierarchical-grid/overview.md
  docfx/jp/components/toc.json
Labels: status: localized

#1236 Add tabs topic for React
  doc/en/components/layouts/tabs.md
  docfx/en/components/toc.json
Labels: status: verified

#1151 [React] Adding all combo topics for React
  doc/en/components/inputs/combo/features.md
  doc/en/components/inputs/combo/overview.md
  doc/en/components/inputs/combo/single-selection.md
  doc/en/components/inputs/combo/templates.md
  docfx/en/components/toc.json
Labels: status: verified, topic: combo, platform: react

#1285 Updating JA - Combo topics, Tabs.
  doc/jp/components/inputs/combo/features.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/inputs/combo/single-selection.md
  doc/jp/components/inputs/combo/templates.md
  doc/jp/components/layouts/tabs.md
  docfx/jp/components/toc.json
Labels: status: localized
