Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-07, with the labels that each got.

#1325 mdd-update-blazor-7-1
  doc/en/components/charts/features/chart-data-selection.md
  docConfig.json
Labels: status: in-review

#1330 Update general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-blazor.md
Labels: :eyes: status: in-review

#1292 docs(banner): add banner topic
  apiMap/WebComponents/webInputs.JS.wc.apiMap.json
  doc/en/components/notifications/banner.md
  docConfig.json
  docfx/en/components/toc.json
Labels: platform: wc, topic: banner

#1338 Update WC changelog
  doc/en/components/general-changelog-dv-wc.md
  docConfig.json
Labels: topic: general, platform: wc

#1336 Updating JA - new Banner topic, other changes.
  doc/jp/components/charts/features/chart-axis-options.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/layouts/divider.md
  doc/jp/components/notifications/banner.md
  doc/jp/components/scheduling/date-picker.md
  docfx/jp/components/toc.json
Labels: status: localized
