Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-11, with the labels that each got.

#1350 Add Carousel topic
  apiMap/WebComponents/webInputs.JS.wc.apiMap.json
  doc/en/components/layouts/carousel.md
  docConfig.json
  docfx/en/components/toc.json
Labels: platform: wc, topic: carousel

#1404 Update JA - Chart Navigation, Button Group
  doc/jp/components/charts/features/chart-navigation.md
  doc/jp/components/inputs/button-group.md
  doc/jp/components/layouts/carousel.md
  docfx/jp/components/toc.json
Labels: status: localized

#1402 Add missing auto gen section and pivot keys add in overview.
  doc/en/components/grids/pivot-grid/overview.md
Labels: status: verified :white_check_mark:

#1410 docs(carousel): add topic for React/Blazor
  apiMap/Blazor/webInputs.JS.blazor.apiMap.json
  apiMap/React/webInputs.JS.r.apiMap.json
  doc/en/components/layouts/carousel.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:, platform: react, platform: blazor, topic: carousel

#1399 Edited documentation for PivotGird topics
  doc/en/components/grids/_shared/state-persistence.md
  doc/en/components/grids/pivot-grid/remote-operations.md
  doc/jp/components/grids/_shared/state-persistence.md
Labels: status: verified :white_check_mark:, platform: blazor, platform: wc
