Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-01, with the labels that each got.

#1114 [JA] Adding the latest topic changes - 23.2, other.
  doc/jp/components/charts/features/chart-highlight-filter.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/advanced-filtering.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  docfx/jp/components/toc.json
Labels: status: localized

#1034 chore(*): update-overview-topics
  doc/en/components/grids/_shared/column-pinning.md
  doc/en/components/grids/theming.md
Labels: topic: grids, status: in-review

#1063 [React] Add TreeGrid cell-editing topic
  doc/en/components/grids/_shared/cell-editing.md
Labels: topic: grids, status: awaiting-test, platform: react, grids: cell-editing

#1120 Updating JA changelogs, other changes.
  doc/jp/components/charts/features/chart-highlight-filter.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/theming.md
Labels: status: localized

#1143 [React] Adding dropdown topic for React
  doc/en/components/inputs/dropdown.md
  docfx/en/components/toc.json
Labels: status: verified, platform: react, topic: drop-down

#1150 [React] Changed button overview info in React
  doc/en/components/inputs/button.md
Labels: status: awaiting-test, platform: react

#1149 [React] Adding the toggle button in the mini navdrawer code snippet in React
  doc/en/components/menus/navigation-drawer.md
Labels: status: awaiting-test, platform: react

#1148 [React] Adding mask input topic for React
  doc/en/components/inputs/mask-input.md
  docfx/en/components/toc.json
Labels: status: verified, platform: react, topic: mask

#1145 [React]: Add Select topic
  doc/en/components/inputs/select.md
  docfx/en/components/toc.json
Labels: status: verified, topic: select, platform: react

#1142 [React]: Add Accordion topic
  doc/en/components/layouts/accordion.md
  docfx/en/components/toc.json
Labels: status: verified, topic: accordion

#1152 Updating JA with the latest changes - inputs, layouts, menus.
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/inputs/mask-input.md
  doc/jp/components/inputs/rating.md
  doc/jp/components/inputs/select.md
  doc/jp/components/layouts/accordion.md
  doc/jp/components/menus/navigation-drawer.md
  docfx/jp/components/toc.json
Labels: status: localized

#1157 Update chart-trendlines.md
  doc/kr/components/charts/features/chart-trendlines.md
Labels: status: in-review

#1147 Add a topic that shows usage of react coponents within Next.js
  doc/en/components/nextjs-usage.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1161 mdd-PackageVerChanges-23-2
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#1162 [JA] Adding Next.js topic, changelog updates.
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-getting-started.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/inputs/input.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/nextjs-usage.md
  docfx/jp/components/toc.json
Labels: status: localized
