Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-08, with the labels that each got.

#1344 Update radial-chart.md
  doc/en/components/charts/types/radial-chart.md
Labels: status: in-review :eyes:

#1342 Updating JA - Web Components changelog
  doc/jp/components/charts/types/data-pie-chart.md
  doc/jp/components/charts/types/radial-chart.md
  doc/jp/components/general-changelog-dv-wc.md
  docfx/jp/components/toc.json
Labels: status: localized

#1345 mdd-update-cc-selection matcher
  doc/en/components/charts/features/chart-data-selection.md
Labels: status: in-review :eyes:

#1340 Update Display Density topic with new --ig-size property and mentions of old property.
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/grids/_shared/column-moving.md
  doc/en/components/grids/_shared/conditional-cell-styling.md
  doc/en/components/grids/_shared/multi-column-headers.md
  doc/en/components/grids/_shared/paging.md
  doc/en/components/grids/_shared/remote-data-operations.md
  doc/en/components/grids/_shared/search.md
  doc/en/components/grids/_shared/size.md
  doc/en/components/grids/_shared/summaries.md
  doc/en/components/grids/data-grid.md
  doc/en/components/grids/grids-header.md
  doc/en/components/grids/pivot-grid/features.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:

#1349 mdd-add-accessibility-topic
  doc/en/components/interactivity/accessibility-compliance.md
  doc/en/images/general/greenCheck.png
  doc/en/images/general/redX.png
  docfx/en/components/toc.json
  stats/docStats-Blazor.json
Labels: status: in-review :eyes:

#1360 Enable Stepper animations section for Blazor
  doc/en/components/layouts/stepper.md
  doc/jp/components/layouts/stepper.md
Labels: status: verified :white_check_mark:, topic: stepper, platform: blazor
