Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-02, with the labels that each got.

#1115 Add section about the toggleNodeOnClick property
  doc/en/components/grids/tree.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1168 update blazor server
  doc/en/components/general-getting-started.md
Labels: status: in-review

#1169 Updating JA for the latest changes - Paste Excel, Tree, Geo Map.
  doc/jp/components/general-getting-started.md
  doc/jp/components/geo-map-display-heat-imagery.md
  doc/jp/components/grids/grid/paste-excel.md
  doc/jp/components/grids/tree.md
  docfx/jp/components/toc.json
Labels: status: localized
