Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2024-06, with the labels that each got.

#1296 [Localization] Updating JA topics with the latest changes - Date Time Input, Column Types, JA URLs
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/hierarchical-grid/load-on-demand.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/layouts/accordion.md
  doc/jp/components/layouts/dock-manager.md
  doc/jp/components/layouts/stepper.md
  docfx/jp/components/toc.json
Labels: status: localized

#1250 Add treeGrid column resizing topic
  doc/en/components/grids/_shared/column-resizing.md
  docfx/en/components/toc.json
Labels: platform: react

#1253 Add treeGrid column types topic
  doc/en/components/grids/_shared/column-types.md
  docfx/en/components/toc.json
Labels: platform: react

#1278 Add tree grid paging topic
  doc/en/components/grids/_shared/paging.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1279 Adding tgrid row-drag topic
  doc/en/components/grids/_shared/row-drag.md
  docfx/en/components/toc.json
Labels: status: verified

#1275 Add tree grid row pinning topic
  doc/en/components/grids/_shared/row-pinning.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1274 Add tree grid row selection topic
  doc/en/components/grids/_shared/row-selection.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1282 Add grid and chart overview pre load static images for code-view
  doc/en/components/charts/chart-overview.md
  doc/en/components/grids/data-grid.md
  doc/jp/components/charts/chart-overview.md
  doc/jp/components/grids/data-grid.md
  doc/kr/components/charts/chart-overview.md
  package-lock.json
  package.json
  src/ext/MarkdownTransformer.ts
  yarn.lock
Labels: status: awaiting-test

#1298 mdd-updates-per-pull/1291
  doc/en/components/charts/features/chart-data-filtering.md
  doc/en/components/charts/types/treemap-chart.md
  doc/en/components/radial-gauge.md
  doc/jp/components/radial-gauge.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  stats/docStats-WC.json
Labels: status: in-development

#1273 Add Tree Grid toolbar topic
  doc/en/components/grids/_shared/toolbar.md
  docfx/en/components/toc.json
Labels: status: awaiting-test, platform: react, platform: blazor, platform: wc, topic: tree-grid

#1266 Add tree grid selection topic
  doc/en/components/grids/_shared/selection.md
  docfx/en/components/toc.json
Labels: status: verified

#1263 Add tree grid multi column headers topic
  doc/en/components/grids/_shared/multi-column-headers.md
  docfx/en/components/toc.json
Labels: status: verified

#1286 Add tree grid summary topic
  doc/en/components/grids/_shared/summaries.md
  docfx/en/components/toc.json
Labels: status: verified

#1259 Add tree grid export excel topic
  doc/en/components/grids/_shared/export-excel.md
  docfx/en/components/toc.json
Labels: status: verified

#1256 Add tree grid editing topic
  doc/en/components/grids/_shared/editing.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1254 Add tree grid column selection topic
  docfx/en/components/toc.json
Labels: status: verified

#1299 Revert "docs(button-group): add React/Blazor topic"
  doc/en/components/inputs/button-group.md
  docfx/en/components/toc.json
Labels: status: verified

#1265 Add tree grid column hiding topic
  doc/en/components/grids/_shared/column-hiding.md
  docfx/en/components/toc.json
Labels: status: verified

#1247 Add tree grid display density topic
  doc/en/components/grids/_shared/display-density.md
  docfx/en/components/toc.json
Labels: status: verified

#1248 Add tree grid sizing topic
  docfx/en/components/toc.json
Labels: status: verified

#1297 Add textarea topic
  doc/en/components/inputs/text-area.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1300 Updating JA topics with the latest changes - 7 June 24
  doc/jp/components/charts/features/chart-data-filtering
  doc/jp/components/charts/features/chart-data-filtering.md
  doc/jp/components/charts/types/treemap-chart.md
  doc/jp/components/editors/date-picker.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/display-density.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/grids/_shared/virtualization.md
  doc/jp/components/grids/grid/paste-excel.md
  doc/jp/components/inputs/text-area.md
  docfx/jp/components/toc.json
Labels: status: localized

#1255 Add tree grid collapsible column groups topic
  doc/en/components/grids/_shared/collapsible-column-groups.md
  docfx/en/components/toc.json
Labels: status: awaiting-test

#1252 Add tree grid row actions topic
  doc/en/components/grids/_shared/row-actions.md
  docfx/en/components/toc.json
Labels: status: verified

#1249 Add tree grid sorting topic
  doc/en/components/grids/_shared/sorting.md
  docfx/en/components/toc.json
Labels: status: verified

#1262 Add tree grid row editing topic
  doc/en/components/grids/_shared/row-editing.md
  docfx/en/components/toc.json
Labels: status: verified

#1303 docs(button-group): add React/Blazor topic
  doc/en/components/inputs/button-group.md
  docfx/en/components/toc.json
Labels: status: awaiting-test, platform: react, platform: blazor, button-group, toggle-button

#1304 docs(tree-grid): enable topics and add statuses
  docfx/en/components/toc.json
Labels: topic: tree-grid

#1287 mdd-data-legendandtooltip-grouping
  doc/en/components/charts/features/chart-data-legend.md
  doc/en/components/charts/features/chart-data-tooltip.md
  doc/en/components/charts/features/chart-highlight-filter.md
Labels: status: in-review

#1301 Updating JA for #1255, content fixes.
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-highlight-filter.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/inputs/button-group.md
  docfx/jp/components/toc.json
Labels: status: localized

#1312 Correct React template in Cell Editing Templates section in Cell Editing topic
  doc/en/components/grids/_shared/cell-editing.md
Labels: status: awaiting-test

#1313 mdd-angular-18.0.0
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review

#1307 mdd-new-6/14
  doc/en/components/charts/features/chart-data-selection.md
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  doc/en/components/radial-gauge.md
  doc/jp/components/charts/features/chart-data-selection.md
  docConfig.json
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: in-review

#1318 chore(*): fix charts cta banner typo
  package-lock.json
  package.json
  yarn.lock
Labels: status: awaiting-test

#1317 Mdd changelog and chart selection
  doc/en/components/charts/features/chart-data-selection.md
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/general-changelog-dv.md
  stats/docStats-Blazor.json
  stats/docStats-React.json
  stats/docStats-WC.json
Labels: status: in-review

#1323 Update chart-data-selection.md
  doc/en/components/charts/features/chart-data-selection.md
Labels: status: in-review

#1324 [JA] Updating Changelogs, new Data Selection topic, other updates.
  doc/jp/components/bullet-graph.md
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-selection.md
  doc/jp/components/charts/types/bubble-chart.md
  doc/jp/components/charts/types/treemap-chart.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/cell-editing.md
  doc/jp/components/grids/_shared/cell-selection.md
  doc/jp/components/grids/data-grid/row-highlighting.md
  doc/jp/components/nextjs-usage.md
  doc/jp/components/radial-gauge.md
  docfx/jp/components/toc.json
Labels: status: localized
