Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-05, with the labels that each got.

#1502 Updating JA changelogs (April release)
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/update-guide.md
  docfx/jp/components/toc.json
Labels: status: localized

#1506 Update collapsible column groups topic for React 19
  doc/en/components/grids/_shared/collapsible-column-groups.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:

#1507 Update column hiding topic for React 19
  doc/en/components/grids/_shared/column-hiding.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:

#1508 Update column moving topic for React 19
  doc/en/components/grids/_shared/column-moving.md
Labels: status: verified :white_check_mark:

#1510 Update column pinning topic for React 19
  doc/en/components/grids/_shared/column-pinning.md
Labels: status: verified :white_check_mark:

#1527 Update tabs topic
  doc/en/components/layouts/tabs.md
Labels: status: awaiting-test :x:

#1538 chart-data-annotations
  doc/en/components/charts/features/chart-data-annotations.md
  doc/en/components/charts/features/chart-overlays.md
  docfx/en/components/toc.json
  docfx/jp/components/toc.json
  docfx/kr/components/toc.json
Labels: status: in-review :eyes:

#1561 Updating JA with the latest changes - data annotations, changelogs.
  doc/jp/components/charts/features/chart-data-annotations.md
  doc/jp/components/charts/features/chart-data-legend.md
  doc/jp/components/charts/features/chart-data-tooltip.md
  doc/jp/components/charts/features/chart-overlays.md
  doc/jp/components/charts/features/chart-trendlines.md
  doc/jp/components/charts/types/data-pie-chart.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/_shared/collapsible-column-groups.md
  doc/jp/components/grids/_shared/column-hiding.md
  doc/jp/components/grids/_shared/column-moving.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/layouts/tabs.md
  doc/jp/images/general/layout_mode.png
  docfx/jp/components/toc.json
Labels: status: localized

#1511 Update column resizing topic for React 19
  doc/en/components/grids/_shared/column-resizing.md
Labels: status: verified :white_check_mark:

#1512 Update conditional cell styling topic for React 19
  doc/en/components/grids/_shared/conditional-cell-styling.md
Labels: status: verified :white_check_mark:

#1528 Update excel style filtering topic for React 19
  doc/en/components/grids/_shared/excel-style-filtering.md
Labels: status: verified :white_check_mark:

#1530 Update row adding topic for React 19
  doc/en/components/grids/_shared/row-adding.md
Labels: status: verified :white_check_mark:

#1537 Update row dragging topic for React 19
  doc/en/components/grids/_shared/row-drag.md
Labels: status: verified :white_check_mark:

#1566 JA - adding the latest updates - 23 may
  doc/jp/components/charts/features/chart-overlays.md
  doc/jp/components/dashboard-tile.md
  doc/jp/components/editors/xdate-picker.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-licensing.md
  doc/jp/components/grids/_shared/column-resizing.md
  doc/jp/components/grids/_shared/column-types.md
  doc/jp/components/grids/_shared/conditional-cell-styling.md
  doc/jp/components/grids/_shared/editing.md
  doc/jp/components/grids/_shared/excel-style-filtering.md
  doc/jp/components/grids/_shared/export-excel.md
  doc/jp/components/grids/_shared/filtering.md
  doc/jp/components/grids/_shared/live-data.md
  doc/jp/components/grids/_shared/multi-column-headers.md
  doc/jp/components/grids/_shared/multi-row-layout.md
  doc/jp/components/grids/_shared/paging.md
  doc/jp/components/grids/_shared/row-actions.md
  doc/jp/components/grids/_shared/row-adding.md
  doc/jp/components/grids/_shared/row-drag.md
  doc/jp/components/grids/_shared/selection.md
  doc/jp/components/grids/_shared/size.md
  doc/jp/components/grids/_shared/state-persistence.md
  doc/jp/components/grids/_shared/toolbar.md
  doc/jp/components/nextjs-usage.md
Labels: status: localized
