Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-06, with the labels that each got.

#1585 Updating JA Tooltip topic for React
  doc/jp/components/dashboard-tile.md
  doc/jp/components/grids/_shared/keyboard-navigation.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/inputs/tooltip.md
  doc/jp/components/menus/toolbar.md
  docfx/jp/components/toc.json
Labels: status: localized

#1547 docs(file-input): add API mapping (vnext)
  apiMap/WebComponents/webInputs.JS.wc.apiMap.json
  doc/en/components/inputs/file-input.md
  docConfig.json
Labels: topic: file-input

#1599 Update general changelog for Blazor
  doc/en/components/general-changelog-dv-blazor.md
Labels: status: localized

#1601 [JA] Changelog and Grid Group By updates
  doc/jp/components/editors/multi-column-combobox.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/grids/grid/groupby.md
  doc/jp/components/inputs/file-input.md
Labels: status: localized

#1499 Update snippets for advanced filtering topic
  doc/en/components/grids/_shared/advanced-filtering.md
Labels: status: verified :white_check_mark:

#1503 Update cell selection topic for react 19
  doc/en/components/grids/_shared/cell-selection.md
Labels: status: verified :white_check_mark:

#1553 Update button topic for v19
  doc/en/components/inputs/button.md
Labels: status: verified :white_check_mark:

#1554 Update checkbox topic to v19
  doc/en/components/inputs/checkbox.md
Labels: status: verified :white_check_mark:

#1581 Update topic for Accordion for react v19
  doc/en/components/layouts/accordion.md
Labels: status: verified :white_check_mark:

#1584 Update topic for Avatar for React v19
  doc/en/components/layouts/avatar.md
Labels: status: verified :white_check_mark:

#1594 Update expansion panel topic for React 19
  doc/en/components/layouts/expansion-panel.md
Labels: status: resolved :white_check_mark:

#1598 Update icon topic for React 19
  doc/en/components/layouts/icon.md
Labels: status: verified :white_check_mark:

#1589 Stepper topic update for React 19
  doc/en/components/layouts/stepper.md
Labels: status: verified :white_check_mark:

#1592 Navbar topic update to 19
  doc/en/components/menus/navbar.md
Labels: status: verified :white_check_mark:

#1613 Dialog topic update to 19
  doc/en/components/notifications/dialog.md
Labels: status: verified :white_check_mark:

#1605 Snackbar overview topic update
  doc/en/components/notifications/snackbar.md
Labels: status: verified :white_check_mark:

#1606 Toast Topic Update to React19
  doc/en/components/notifications/toast.md
Labels: status: verified :white_check_mark:

#1610 Calendar topic update to react 19
  doc/en/components/scheduling/calendar.md
Labels: status: verified :white_check_mark:

#1540 Update search topic for React 19
  doc/en/components/grids/_shared/search.md
Labels: status: verified :white_check_mark:

#1569 Update date time input topic for React 19
  doc/en/components/inputs/date-time-input.md
Labels: status: verified :white_check_mark:

#1575 Update mask input topic for React 19
  doc/en/components/inputs/mask-input.md
Labels: status: verified :white_check_mark:

#1576 Update radio topic for React 19
  doc/en/components/inputs/radio.md
Labels: status: verified :white_check_mark:

#1578 Update rating topic for React 19
  doc/en/components/inputs/rating.md
Labels: status: verified :white_check_mark:

#1620 JA - updating snippets for React 19, other file updates to match EN
  doc/jp/components/grids/_shared/remote-data-operations.md
  doc/jp/components/grids/_shared/row-editing.md
  doc/jp/components/grids/_shared/row-pinning.md
  doc/jp/components/grids/_shared/row-selection.md
  doc/jp/components/grids/_shared/search.md
  doc/jp/components/grids/_shared/sorting.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/grids/data-grid.md
  doc/jp/components/grids/grid/master-detail.md
  doc/jp/components/grids/grid/paste-excel.md
  doc/jp/components/grids/grids-header.md
  doc/jp/components/grids/hierarchical-grid/load-on-demand.md
  doc/jp/components/grids/hierarchical-grid/overview.md
  doc/jp/components/grids/list.md
  doc/jp/components/grids/pivot-grid/features.md
  doc/jp/components/grids/pivot-grid/overview.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/combo/features.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/inputs/combo/templates.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/mask-input.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/rating.md
  doc/jp/components/inputs/ripple.md
  doc/jp/components/inputs/select.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/inputs/text-area.md
  doc/jp/components/notifications/dialog.md
  doc/jp/components/notifications/snackbar.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/scheduling/calendar.md
  doc/jp/components/scheduling/date-picker.md
Labels: status: localized

#1505 Update cascading combos topic for React 19
  doc/en/components/grids/_shared/cascading-combos.md
Labels: status: verified :white_check_mark:

#1525 docs(date-range-picker): add date range picker topic
  apiMap/WebComponents/webInputs.JS.wc.apiMap.json
  doc/en/components/scheduling/date-range-picker.md
  docConfig.json
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:, topic: date-range-picker
