Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-07, with the labels that each got.

#1587 Add react api docs override for new separate apis. Api overrides for whole packages.
  docConfig.json
  src/ext/MarkdownTransformer.ts
Labels: status: verified :white_check_mark:

#1624 [JA] Code snippet updates, new Date Range Picker topic
  doc/jp/components/grids/_shared/cascading-combos.md
  doc/jp/components/notifications/banner.md
  doc/jp/components/scheduling/date-range-picker.md
  docfx/jp/components/toc.json
Labels: status: localized

#1627 Update Tile Manager topic for React and Blazor
  doc/en/components/layouts/tile-manager.md
  docfx/en/components/toc.json
Labels: tile-manager

#1634 Fix wc api links missing underscore.
  src/ext/MarkdownTransformer.ts
Labels: status: verified :white_check_mark:

#1646 [JA] July SR changelog updates
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
Labels: status: localized

#1652 mdd-update### {PackageCharts} (Charts)
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
Labels: status: in-review :eyes:

#1653 [JA] July changelog fixes
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
Labels: status: localized
