Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-09, with the labels that each got.

#1675 [JA] Update React changelog (19.2.1)
  doc/jp/components/general-changelog-dv-react.md
Labels: topic: general, status: localized

#1670 [JA] Tooltip topic updates, Blazor changelog fix
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/inputs/tooltip.md
Labels: status: localized, topic: tooltip

#1692 [JA] Azure Maps topic
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/geo-map-display-azure-imagery.md
  doc/jp/images/general/AzureMapsImagery.png
  docfx/jp/components/toc.json
Labels: topic: maps, status: localized

#1691 chore(*): Adding a topic for Chat component
  doc/en/components/interactivity/chat.md
  docfx/en/components/toc.json
  stats/docStats-Angular.json
  stats/docStats-React.json
  stats/docStats-WC.json
Labels: status: pending-localization :symbols:

#1698 mdd-increase-height-azure-iframe
  doc/en/components/geo-map-display-azure-imagery.md
  doc/jp/components/geo-map-display-azure-imagery.md
Labels: status: in-review :eyes:

#1699 mdd-update-imagery-options
  doc/en/components/geo-map-display-azure-imagery.md
Labels: status: in-review :eyes:

#1700 mdd-update-40126
  doc/en/components/geo-map-display-azure-imagery.md
  doc/en/images/general/Azure_Traffic_Tile_Series_With_Background.png
Labels: status: in-review :eyes:

#1701 mdd-update-parity-between-angular
  doc/en/components/geo-map-display-azure-imagery.md
Labels: status: in-review :eyes:

#1707 mdd-more-fixes-azure-map
  doc/en/components/geo-map-display-azure-imagery.md
Labels: status: resolved :white_check_mark:
