Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-04, with the labels that each got.

#1481 [JA] Tile Manager update, Blazor Maui topic fix.
  doc/jp/components/general-getting-started-blazor-maui.md
  doc/jp/components/layouts/tile-manager.md
Labels: status: localized

#1482 [JA] Fixing Blazor Maui topic - master
  doc/jp/components/general-getting-started-blazor-maui.md
Labels: status: localized

#1478 docs(react): add changelog for 18.8.1 react patch
  doc/en/components/general-changelog-dv-react.md
  docConfig.json
Labels: status: verified :white_check_mark:

#1485 doc(*): add initial filtering section and changelogs
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  doc/en/components/grids/_shared/filtering.md
  docConfig.json
Labels: status: verified :white_check_mark:

#1493 Updating JA changelogs (April 2025)
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/grids/_shared/filtering.md
Labels: status: localized

#1491 docs(tooltip): add tooltip topic (vnext)
  apiMap/WebComponents/webInputs.JS.wc.apiMap.json
  doc/en/components/inputs/tooltip.md
  docConfig.json
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:, platform: wc, status: pending-localization :symbols:, topic: tooltip

#1495 mdd-web-app-topic
  doc/en/components/general-getting-started-blazor-web-app.md
  doc/en/images/general/new-blazor-project-configuring-web-app.jpg
  doc/en/images/general/new-blazor-project-web-app-info.jpg
  doc/en/images/general/new-blazor-project-web-app.jpg
  docfx/en/components/toc.json
Labels: status: in-review :eyes:

#1487 docs(file-input): add file input topic (vnext)
  doc/en/components/inputs/file-input.md
  docfx/en/components/toc.json
Labels: topic: file-input

#1497 [JA] New Topics - File Input, Tooltip, Blazor Web App
  doc/jp/components/general-getting-started-blazor-web-app.md
  doc/jp/components/inputs/file-input.md
  doc/jp/components/inputs/tooltip.md
  doc/jp/images/general/new-blazor-project-configuring-web-app.jpg
  doc/jp/images/general/new-blazor-project-web-app-info.jpg
  doc/jp/images/general/new-blazor-project-web-app.jpg
  docfx/jp/components/toc.json
Labels: status: localized

#1498 Add react update guide from 18.9.0 to 19.0.0
  doc/en/components/update-guide.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:
