Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-02, with the labels that each got.

#1414 docs(dock-manager): add split panes fixed size section
  doc/en/components/layouts/dock-manager-customization.md
  doc/en/components/layouts/dock-manager.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:

#1375 docs(grids): added remote samples topic for grid and hgrid
  doc/en/components/grids/_shared/remote-data-operations.md
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:

#1456 mdd-31906
  doc/en/components/menus/toolbar.md
Labels: status: in-review :eyes:

#1457 mdd-31905
  doc/en/components/menus/toolbar.md
Labels: status: in-review :eyes:

#1455 docs(tile-manager): add tile manager topic
  doc/en/components/layouts/tile-manager.md
  doc/en/images/tile-manager-actions.png
  docfx/en/components/toc.json
Labels: topic: dv, tile-manager
