Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-03, with the labels that each got.

#1459 [JA] Update Toolbar topic
  doc/jp/components/menus/toolbar.md
Labels: status: localized

#1465 Updating JA with the latest changes - Changelogs, styling
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
  doc/jp/components/general-cli-overview.md
  doc/jp/components/grids/_shared/column-pinning.md
  doc/jp/components/grids/list.md
  doc/jp/components/grids/tree.md
  doc/jp/components/inputs/badge.md
  doc/jp/components/inputs/button-group.md
  doc/jp/components/inputs/button.md
  doc/jp/components/inputs/checkbox.md
  doc/jp/components/inputs/chip.md
  doc/jp/components/inputs/circular-progress.md
  doc/jp/components/inputs/combo/overview.md
  doc/jp/components/inputs/date-time-input.md
  doc/jp/components/inputs/dropdown.md
  doc/jp/components/inputs/icon-button.md
  doc/jp/components/inputs/input.md
  doc/jp/components/inputs/linear-progress.md
  doc/jp/components/inputs/mask-input.md
  doc/jp/components/inputs/radio.md
  doc/jp/components/inputs/rating.md
  doc/jp/components/inputs/ripple.md
  doc/jp/components/inputs/select.md
  doc/jp/components/inputs/slider.md
  doc/jp/components/inputs/switch.md
  doc/jp/components/inputs/text-area.md
  doc/jp/components/layouts/avatar.md
  doc/jp/components/layouts/card.md
  doc/jp/components/layouts/expansion-panel.md
  doc/jp/components/layouts/icon.md
  doc/jp/components/layouts/stepper.md
  doc/jp/components/layouts/tabs.md
  doc/jp/components/menus/navbar.md
  doc/jp/components/menus/navigation-drawer.md
  doc/jp/components/notifications/banner.md
  doc/jp/components/notifications/dialog.md
  doc/jp/components/notifications/snackbar.md
  doc/jp/components/notifications/toast.md
  doc/jp/components/scheduling/calendar.md
  doc/jp/components/scheduling/date-picker.md
  doc/jp/components/themes/configuration.md
  doc/jp/components/themes/elevations.md
  doc/jp/components/themes/overview.md
  doc/jp/components/themes/palettes.md
  doc/jp/components/themes/styles.md
  docfx/jp/components/toc.json
Labels: status: localized

#1469 mdd- 33214 - Update chart-data-selection.md
  doc/en/components/charts/features/chart-data-selection.md
Labels: status: in-review :eyes:

#1460 docs(tile-manager): additional tile manager doc changes
  doc/en/components/layouts/tile-manager.md
  doc/en/images/tile-manager-actions.png
  docfx/en/components/toc.json
Labels: status: in-development :hammer_and_wrench:, tile-manager

#1472 fix(*): Removed the row-count prop
  doc/en/components/layouts/tile-manager.md
Labels: tile-manager

#1437 docs(dock-manager): add docking section
  doc/en/components/layouts/dock-manager.md
  doc/en/images/dockmanager-document-host-docking.jpg
  doc/en/images/dockmanager-pane-docking.jpg
  doc/en/images/dockmanager-root-docking.jpg
  doc/en/images/dockmanager-splitter-docking.jpg
  docfx/en/components/toc.json
Labels: status: verified :white_check_mark:

#1475 Update JA - Tile Manager, Changelogs, other changes.
  doc/jp/components/charts/features/chart-data-selection.md
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/grids/_shared/summaries.md
  doc/jp/components/layouts/tile-manager.md
  doc/jp/images/tile-manager-actions.png
  docfx/jp/components/toc.json
Labels: status: localized

#1477 [JA] Update Dock Manager topic
  doc/jp/components/layouts/dock-manager.md
  doc/jp/images/dockmanager-document-host-docking.jpg
  doc/jp/images/dockmanager-pane-docking.jpg
  doc/jp/images/dockmanager-root-docking.jpg
  doc/jp/images/dockmanager-splitter-docking.jpg
  docfx/jp/components/toc.json
Labels: status: localized

#1474 docs(tile-manager): add snapping section in resizing
  doc/en/components/layouts/tile-manager.md
Labels: status: in-test :boom:, status: verified :white_check_mark:, tile-manager
