Repository IgniteUI/igniteui-xplat-docs, pull requests merged in 2025-01, with the labels that each got.

#1433 JA changelog updates to match EN - Color Editor.
  doc/jp/components/general-changelog-dv-blazor.md
  doc/jp/components/general-changelog-dv-react.md
  doc/jp/components/general-changelog-dv-wc.md
  doc/jp/components/general-changelog-dv.md
Labels: status: localized

#1438 mdd-angular-19-changelog
  doc/en/components/general-changelog-dv.md
  docConfig.json
Labels: status: in-review :eyes:

#1440 mdd-jan-2025-changelog
  doc/en/components/general-changelog-dv-blazor.md
  doc/en/components/general-changelog-dv-react.md
  doc/en/components/general-changelog-dv-wc.md
  docConfig.json
Labels: status: verified :white_check_mark:
